"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, TYPE_CHECKING
from typing_extensions import TypedDict
from collections.abc import Coroutine
from graphql import GraphQLFormattedError

if TYPE_CHECKING:
    ...
@dataclass
class Response:
    errors: list[GraphQLFormattedError] | None
    data: dict[str, Any] | None
    extensions: dict[str, Any] | None
    ...


class Body(TypedDict, total=False):
    query: str
    variables: dict[str, object] | None
    ...


class BaseGraphQLTestClient(ABC):
    def __init__(self, client: Any, url: str = ...) -> None:
        ...
    
    def query(self, query: str, variables: dict[str, Any] | None = ..., headers: dict[str, object] | None = ..., asserts_errors: bool | None = ..., files: dict[str, object] | None = ..., assert_no_errors: bool | None = ...) -> Coroutine[Any, Any, Response] | Response:
        ...
    
    @abstractmethod
    def request(self, body: dict[str, object], headers: dict[str, object] | None = ..., files: dict[str, object] | None = ...) -> Any:
        ...
    


__all__ = ["BaseGraphQLTestClient", "Body", "Response"]
