"""
This type stub file was generated by pyright.
"""

from typing import Any
from graphql import ArgumentNode, GraphQLNamedType, ObjectValueNode, ValidationContext, ValidationRule

class MaybeNullValidationRule(ValidationRule):
    """Validates that Maybe[T] fields do not receive explicit null values.

    This rule ensures that:
    - Maybe[T] fields can only be omitted or have non-null values
    - Maybe[T | None] fields can be omitted, null, or have non-null values

    This provides clear semantics where Maybe[T] means "either present with value or absent"
    and Maybe[T | None] means "present with value, present but null, or absent".
    """
    def __init__(self, validation_context: ValidationContext) -> None:
        ...
    
    def enter_argument(self, node: ArgumentNode, *_args: Any) -> None:
        ...
    
    def enter_object_value(self, node: ObjectValueNode, *_args: Any) -> None:
        ...
    
    def validate_maybe_fields(self, node: ObjectValueNode, input_type: GraphQLNamedType, strawberry_type: Any) -> None:
        ...
    


__all__ = ["MaybeNullValidationRule"]
