"""
This type stub file was generated by pyright.
"""

from typing import Any
from graphql import ExecutableDefinitionNode, GraphQLNamedType, ObjectValueNode, ValidationContext, ValidationRule, VariableDefinitionNode

class OneOfInputValidationRule(ValidationRule):
    def __init__(self, validation_context: ValidationContext) -> None:
        ...
    
    def enter_operation_definition(self, node: ExecutableDefinitionNode, *_args: Any) -> None:
        ...
    
    def enter_variable_definition(self, node: VariableDefinitionNode, *_args: Any) -> None:
        ...
    
    def enter_object_value(self, node: ObjectValueNode, *_args: Any) -> None:
        ...
    
    def validate_one_of(self, node: ObjectValueNode, type: GraphQLNamedType) -> None:
        ...
    


__all__ = ["OneOfInputValidationRule"]
