"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from strawberry.cli.app import app

@app.command(help="Generate code from a query")
def codegen(query: list[Path] | None = ..., schema: str = ..., app_dir: str = ..., output_dir: Path = ..., selected_plugins: list[str] = ..., cli_plugin: str | None = ...) -> None:
    ...

