"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from strawberry.cli.app import app

@app.command(help="Exports the schema")
def export_schema(schema: str, app_dir: str = ..., output: Path = ...) -> None:
    ...

