"""
This type stub file was generated by pyright.
"""

from strawberry.cli.app import app

err_console = ...
@app.command(help="Locate a definition in the schema (output: path:line:column)")
def locate_definition(schema: str, symbol: str, app_dir: str = ...) -> None:
    ...

