"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from strawberry.cli.app import app

@app.command(help="Generate code from a query")
def schema_codegen(schema: Path = ..., output: Path | None = ...) -> None:
    ...

