"""
This type stub file was generated by pyright.
"""

from functools import cached_property
from typing import TYPE_CHECKING
from strawberry.exceptions.exception import StrawberryException
from strawberry.exceptions.exception_source import ExceptionSource
from strawberry.types.fields.resolver import StrawberryResolver

if TYPE_CHECKING:
    ...
class NodeIDAnnotationError(StrawberryException):
    def __init__(self, message: str, cls: type) -> None:
        ...
    
    @cached_property
    def exception_source(self) -> ExceptionSource | None:
        ...
    


class RelayWrongAnnotationError(StrawberryException):
    def __init__(self, field_name: str, cls: type) -> None:
        ...
    
    @cached_property
    def exception_source(self) -> ExceptionSource | None:
        ...
    


class RelayWrongResolverAnnotationError(StrawberryException):
    def __init__(self, field_name: str, resolver: StrawberryResolver) -> None:
        ...
    
    @cached_property
    def exception_source(self) -> ExceptionSource | None:
        ...
    


__all__ = ["NodeIDAnnotationError", "RelayWrongAnnotationError", "RelayWrongResolverAnnotationError"]
