"""
This type stub file was generated by pyright.
"""

import strawberry
from collections.abc import Awaitable, Callable, Mapping, Sequence
from typing import Any, Literal, TYPE_CHECKING
from strawberry.extensions.field_extension import AsyncExtensionResolver, FieldExtension, SyncExtensionResolver
from strawberry.types.field import StrawberryField, _RESOLVER_TYPE
from .types import Connection, GlobalID, Node
from strawberry.permission import BasePermission

if TYPE_CHECKING:
    ...
class NodeExtension(FieldExtension):
    def apply(self, field: StrawberryField) -> None:
        ...
    
    def resolve(self, next_: SyncExtensionResolver, source: Any, info: strawberry.Info, **kwargs: Any) -> Any:
        ...
    
    async def resolve_async(self, next_: SyncExtensionResolver, source: Any, info: strawberry.Info, **kwargs: Any) -> Any:
        ...
    
    def get_node_resolver(self, field: StrawberryField) -> Callable[[strawberry.Info, GlobalID], Node | None | Awaitable[Node | None]]:
        ...
    
    def get_node_list_resolver(self, field: StrawberryField) -> Callable[[strawberry.Info, list[GlobalID]], list[Node] | Awaitable[list[Node]]]:
        ...
    


class ConnectionExtension(FieldExtension):
    connection_type: type[Connection[Node]]
    def __init__(self, max_results: int | None = ...) -> None:
        ...
    
    def apply(self, field: StrawberryField) -> None:
        ...
    
    def resolve(self, next_: SyncExtensionResolver, source: Any, info: strawberry.Info, *, before: str | None = ..., after: str | None = ..., first: int | None = ..., last: int | None = ..., **kwargs: Any) -> Any:
        ...
    
    async def resolve_async(self, next_: AsyncExtensionResolver, source: Any, info: strawberry.Info, *, before: str | None = ..., after: str | None = ..., first: int | None = ..., last: int | None = ..., **kwargs: Any) -> Any:
        ...
    


if TYPE_CHECKING:
    node = ...
else:
    ...
ConnectionGraphQLType = Any
def connection(graphql_type: ConnectionGraphQLType | None = ..., *, resolver: _RESOLVER_TYPE[Any] | None = ..., name: str | None = ..., is_subscription: bool = ..., description: str | None = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., max_results: int | None = ..., init: Literal[True, False] | None = ...) -> Any:
    """Annotate a property or a method to create a relay connection field.

    Relay connections are mostly used for pagination purposes. This decorator
    helps creating a complete relay endpoint that provides default arguments
    and has a default implementation for the connection slicing.

    Note that when setting a resolver to this field, it is expected for this
    resolver to return an iterable of the expected node type, not the connection
    itself. That iterable will then be paginated accordingly. So, the main use
    case for this is to provide a filtered iterable of nodes by using some custom
    filter arguments.

    Args:
        graphql_type: The type of the nodes in the connection. This is used to
            determine the type of the edges and the node field in the connection.
        resolver: The resolver for the connection. This is expected to return an
            iterable of the expected node type.
        name: The GraphQL name of the field.
        is_subscription: Whether the field is a subscription.
        description: The GraphQL description of the field.
        permission_classes: The permission classes to apply to the field.
        deprecation_reason: The deprecation reason of the field.
        default: The default value of the field.
        default_factory: The default factory of the field.
        metadata: The metadata of the field.
        directives: The directives to apply to the field.
        extensions: The extensions to apply to the field.
        max_results: The maximum number of results this connection can return.
            Can be set to override the default value of 100 defined in the
            schema configuration.
        init: Used only for type checking purposes.

    Examples:
    Annotating something like this:

    ```python
    @strawberry.type
    class X:
        some_node: relay.Connection[SomeType] = relay.connection(
            resolver=get_some_nodes,
            description="ABC",
        )

        @relay.connection(relay.Connection[SomeType], description="ABC")
        def get_some_nodes(self, age: int) -> Iterable[SomeType]: ...
    ```

    Will produce a query like this:

    ```graphql
    query {
        someNode (
            before: String
            after: String
            first: String
            after: String
            age: Int
        ) {
            totalCount
            pageInfo {
                hasNextPage
                hasPreviousPage
                startCursor
                endCursor
            }
            edges {
                cursor
                node {
                    id
                    ...
                }
            }
        }
    }
    ```

    .. _Relay connections:
        https://relay.dev/graphql/connections.htm

    """
    ...

__all__ = ["connection", "node"]
