"""
This type stub file was generated by pyright.
"""

import dataclasses
import strawberry
from typing import Any, TYPE_CHECKING
from typing_extensions import Self
from strawberry.types.base import StrawberryObjectDefinition

if TYPE_CHECKING:
    ...
def from_base64(value: str) -> tuple[str, str]:
    """Parse the base64 encoded relay value.

    Args:
        value:
            The value to be parsed

    Returns:
        A tuple of (TypeName, NodeID).

    Raises:
        ValueError:
            If the value is not in the expected format

    """
    ...

def to_base64(type_: str | type | StrawberryObjectDefinition, node_id: Any) -> str:
    """Encode the type name and node id to a base64 string.

    Args:
        type_:
            The GraphQL type, type definition or type name.
        node_id:
            The node id itself

    Returns:
        A GlobalID, which is a string resulting from base64 encoding <TypeName>:<NodeID>.

    Raises:
        ValueError:
            If the value is not a valid GraphQL type or name

    """
    ...

def should_resolve_list_connection_edges(info: strawberry.Info) -> bool:
    """Check if the user requested to resolve the `edges` field of a connection.

    Args:
        info:
            The strawberry execution info resolve the type name from

    Returns:
        True if the user requested to resolve the `edges` field of a connection, False otherwise.

    """
    ...

@dataclasses.dataclass
class SliceMetadata:
    start: int
    end: int
    expected: int | None
    @property
    def overfetch(self) -> int:
        ...
    
    @classmethod
    def from_arguments(cls, info: strawberry.Info, *, before: str | None = ..., after: str | None = ..., first: int | None = ..., last: int | None = ..., max_results: int | None = ..., prefix: str | None = ...) -> Self:
        """Get the slice metadata to use on ListConnection."""
        ...
    


__all__ = ["SliceMetadata", "from_base64", "should_resolve_list_connection_edges", "to_base64"]
