"""
This type stub file was generated by pyright.
"""

from strawberry.types.scalar import ScalarDefinition

DEFAULT_SCALAR_REGISTRY: dict[object, ScalarDefinition] = ...
__all__ = ["DEFAULT_SCALAR_REGISTRY", "_make_scalar_definition", "_make_scalar_type"]
