"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING, TypeVar
from typing_extensions import Protocol
from pydantic import BaseModel
from strawberry.types.base import StrawberryObjectDefinition

if TYPE_CHECKING:
    ...
PydanticModel = TypeVar("PydanticModel", bound=BaseModel)
class StrawberryTypeFromPydantic(Protocol[PydanticModel]):
    """This class does not exist in runtime.

    It only makes the methods below visible for IDEs.
    """
    def __init__(self, **kwargs: Any) -> None:
        ...
    
    @staticmethod
    def from_pydantic(instance: PydanticModel, extra: dict[str, Any] | None = ...) -> StrawberryTypeFromPydantic[PydanticModel]:
        ...
    
    def to_pydantic(self, **kwargs: Any) -> PydanticModel:
        ...
    
    @property
    def __strawberry_definition__(self) -> StrawberryObjectDefinition:
        ...
    


