"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    ...
def convert_pydantic_model_to_strawberry_class(cls, *, model_instance=..., extra=...) -> Any:
    ...

def convert_strawberry_class_to_pydantic_model(obj: type) -> Any:
    ...

