"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from pydantic import BaseModel
from strawberry.experimental.pydantic._compat import CompatModelField
from collections.abc import Callable, Sequence

if TYPE_CHECKING:
    ...
def get_type_for_field(field: CompatModelField) -> type[None | list] | Any:
    ...

def field_type_to_type(type_: type) -> Any | list[Any] | None:
    ...

def error_type(model: type[BaseModel], *, fields: list[str] | None = ..., name: str | None = ..., description: str | None = ..., directives: Sequence[object] | None = ..., all_fields: bool = ...) -> Callable[..., type]:
    ...

