"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from pydantic import BaseModel
from pydantic.typing import NoArgAnyCallable

if TYPE_CHECKING:
    ...
class MissingFieldsListError(Exception):
    def __init__(self, type: type[BaseModel]) -> None:
        ...
    


class UnsupportedTypeError(Exception):
    ...


class UnregisteredTypeException(Exception):
    def __init__(self, type: type[BaseModel]) -> None:
        ...
    


class BothDefaultAndDefaultFactoryDefinedError(Exception):
    def __init__(self, default: Any, default_factory: NoArgAnyCallable) -> None:
        ...
    


class AutoFieldsNotInBaseModelError(Exception):
    def __init__(self, fields: list[str], cls_name: str, model: type[BaseModel]) -> None:
        ...
    


