"""
This type stub file was generated by pyright.
"""

from typing import Any
from strawberry.experimental.pydantic._compat import PydanticCompat

def replace_pydantic_types(type_: Any, is_input: bool) -> Any:
    ...

def replace_types_recursively(type_: Any, is_input: bool, compat: PydanticCompat) -> Any:
    """Runs the conversions recursively into the arguments of generic types if any."""
    ...

