"""
This type stub file was generated by pyright.
"""

import builtins
from typing import TYPE_CHECKING
from strawberry.experimental.pydantic._compat import CompatModelField, PydanticCompat
from collections.abc import Callable, Sequence
from strawberry.experimental.pydantic.conversion_types import PydanticModel, StrawberryTypeFromPydantic

if TYPE_CHECKING:
    ...
def get_type_for_field(field: CompatModelField, is_input: bool, compat: PydanticCompat): # -> UnionType | Any:
    ...

if TYPE_CHECKING:
    ...
def type(model: builtins.type[PydanticModel], *, fields: list[str] | None = ..., name: str | None = ..., is_input: bool = ..., is_interface: bool = ..., description: str | None = ..., directives: Sequence[object] | None = ..., all_fields: bool = ..., include_computed: bool = ..., use_pydantic_alias: bool = ...) -> Callable[..., builtins.type[StrawberryTypeFromPydantic[PydanticModel]]]:
    ...

def input(model: builtins.type[PydanticModel], *, fields: list[str] | None = ..., name: str | None = ..., is_interface: bool = ..., description: str | None = ..., directives: Sequence[object] | None = ..., all_fields: bool = ..., use_pydantic_alias: bool = ...) -> Callable[..., builtins.type[StrawberryTypeFromPydantic[PydanticModel]]]:
    """Convenience decorator for creating an input type from a Pydantic model.

    Equal to `partial(type, is_input=True)`

    See https://github.com/strawberry-graphql/strawberry/issues/1830.
    """
    ...

def interface(model: builtins.type[PydanticModel], *, fields: list[str] | None = ..., name: str | None = ..., is_input: bool = ..., description: str | None = ..., directives: Sequence[object] | None = ..., all_fields: bool = ..., use_pydantic_alias: bool = ...) -> Callable[..., builtins.type[StrawberryTypeFromPydantic[PydanticModel]]]:
    """Convenience decorator for creating an interface type from a Pydantic model.

    Equal to `partial(type, is_interface=True)`

    See https://github.com/strawberry-graphql/strawberry/issues/1830.
    """
    ...

