"""
This type stub file was generated by pyright.
"""

import dataclasses
from typing import Any, NamedTuple, TYPE_CHECKING
from pydantic import BaseModel
from strawberry.experimental.pydantic._compat import CompatModelField, PydanticCompat
from pydantic.typing import NoArgAnyCallable

if TYPE_CHECKING:
    ...
def normalize_type(type_: type) -> Any:
    ...

def get_strawberry_type_from_model(type_: Any) -> Any:
    ...

def get_private_fields(cls: type) -> list[dataclasses.Field]:
    ...

class DataclassCreationFields(NamedTuple):
    """Fields required for the fields parameter of make_dataclass."""
    name: str
    field_type: type
    field: dataclasses.Field
    def to_tuple(self) -> tuple[str, type, dataclasses.Field]:
        ...
    


def get_default_factory_for_field(field: CompatModelField, compat: PydanticCompat) -> NoArgAnyCallable | dataclasses._MISSING_TYPE:
    """Gets the default factory for a pydantic field.

    Handles mutable defaults when making the dataclass by
    using pydantic's smart_deepcopy

    Returns optionally a NoArgAnyCallable representing a default_factory parameter
    """
    ...

def ensure_all_auto_fields_in_pydantic(model: type[BaseModel], auto_fields: set[str], cls_name: str, include_computed: bool = ...) -> None:
    ...

