"""
This type stub file was generated by pyright.
"""

from strawberry.fastapi.context import BaseContext
from strawberry.fastapi.router import GraphQLRouter

__all__ = ["BaseContext", "GraphQLRouter"]
