"""
This type stub file was generated by pyright.
"""

from typing import Any, Union
from starlette.background import BackgroundTasks
from starlette.requests import Request
from starlette.responses import Response
from starlette.websockets import WebSocket

CustomContext = Union["BaseContext", dict[str, Any]]
MergedContext = Union["BaseContext", dict[str, Any | BackgroundTasks | Request | Response | WebSocket]]
class BaseContext:
    connection_params: Any | None = ...
    def __init__(self) -> None:
        ...
    


__all__ = ["BaseContext"]
