"""
This type stub file was generated by pyright.
"""

from datetime import timedelta
from typing import Any, TYPE_CHECKING, TypeGuard
from cross_web import StarletteRequestAdapter
from fastapi import APIRouter, Depends, params
from fastapi.routing import APIRoute
from starlette.requests import Request
from starlette.responses import HTMLResponse, Response
from starlette.websockets import WebSocket
from strawberry.http.async_base_view import AsyncBaseHTTPView
from strawberry.http.typevars import Context, RootValue
from collections.abc import AsyncIterator, Awaitable, Callable, Sequence
from enum import Enum
from starlette.routing import BaseRoute
from starlette.types import ASGIApp, Lifespan
from strawberry.http import GraphQLHTTPResponse
from strawberry.http.ides import GraphQL_IDE
from strawberry.schema import BaseSchema

if TYPE_CHECKING:
    ...
class GraphQLRouter(AsyncBaseHTTPView[Request, Response, Response, WebSocket, WebSocket, Context, RootValue], APIRouter):
    allow_queries_via_get = ...
    request_adapter_class = StarletteRequestAdapter
    websocket_adapter_class = ...
    def __init__(self, schema: BaseSchema, path: str = ..., graphiql: bool | None = ..., graphql_ide: GraphQL_IDE | None = ..., allow_queries_via_get: bool = ..., keep_alive: bool = ..., keep_alive_interval: float = ..., root_value_getter: Callable[[], RootValue] | None = ..., context_getter: Callable[..., Context | None | Awaitable[Context | None]] | None = ..., subscription_protocols: Sequence[str] = ..., connection_init_wait_timeout: timedelta = ..., prefix: str = ..., tags: list[str | Enum] | None = ..., dependencies: Sequence[params.Depends] | None = ..., default_response_class: type[Response] = ..., responses: dict[int | str, dict[str, Any]] | None = ..., callbacks: list[BaseRoute] | None = ..., routes: list[BaseRoute] | None = ..., redirect_slashes: bool = ..., default: ASGIApp | None = ..., dependency_overrides_provider: Any | None = ..., route_class: type[APIRoute] = ..., on_startup: Sequence[Callable[[], Any]] | None = ..., on_shutdown: Sequence[Callable[[], Any]] | None = ..., lifespan: Lifespan[Any] | None = ..., deprecated: bool | None = ..., include_in_schema: bool = ..., generate_unique_id_function: Callable[[APIRoute], str] = ..., multipart_uploads_enabled: bool = ..., **kwargs: Any) -> None:
        ...
    
    async def render_graphql_ide(self, request: Request) -> HTMLResponse:
        ...
    
    async def get_context(self, request: Request | WebSocket, response: Response | WebSocket) -> Context:
        ...
    
    async def get_root_value(self, request: Request | WebSocket) -> RootValue | None:
        ...
    
    async def get_sub_response(self, request: Request) -> Response:
        ...
    
    def create_response(self, response_data: GraphQLHTTPResponse | list[GraphQLHTTPResponse], sub_response: Response) -> Response:
        ...
    
    async def create_streaming_response(self, request: Request, stream: Callable[[], AsyncIterator[str]], sub_response: Response, headers: dict[str, str]) -> Response:
        ...
    
    def is_websocket_request(self, request: Request | WebSocket) -> TypeGuard[WebSocket]:
        ...
    
    async def pick_websocket_subprotocol(self, request: WebSocket) -> str | None:
        ...
    
    async def create_websocket_response(self, request: WebSocket, subprotocol: str | None) -> WebSocket:
        ...
    


__all__ = ["GraphQLRouter"]
