"""
This type stub file was generated by pyright.
"""

import logging
from typing import Any, Generic, TYPE_CHECKING
from graphql import GraphQLError
from strawberry.http.typevars import Context, RootValue
from strawberry.subscriptions.protocols.graphql_transport_ws.types import CompleteMessage, ConnectionInitMessage, Message, PingMessage, PongMessage, SubscribeMessage
from strawberry.types import ExecutionResult
from strawberry.types.graphql import OperationType
from datetime import timedelta
from strawberry.http.async_base_view import AsyncBaseHTTPView, AsyncWebSocketAdapter
from strawberry.schema import BaseSchema

if TYPE_CHECKING:
    ...
class BaseGraphQLTransportWSHandler(Generic[Context, RootValue]):
    task_logger: logging.Logger = ...
    def __init__(self, view: AsyncBaseHTTPView[Any, Any, Any, Any, Any, Context, RootValue], websocket: AsyncWebSocketAdapter, context: Context, root_value: RootValue | None, schema: BaseSchema, connection_init_wait_timeout: timedelta) -> None:
        ...
    
    async def handle(self) -> None:
        ...
    
    async def shutdown(self) -> None:
        ...
    
    def on_request_accepted(self) -> None:
        ...
    
    async def handle_connection_init_timeout(self) -> None:
        ...
    
    async def handle_task_exception(self, error: Exception) -> None:
        ...
    
    async def handle_message(self, message: Message) -> None:
        ...
    
    async def handle_connection_init(self, message: ConnectionInitMessage) -> None:
        ...
    
    async def handle_ping(self, message: PingMessage) -> None:
        ...
    
    async def handle_pong(self, message: PongMessage) -> None:
        ...
    
    async def handle_subscribe(self, message: SubscribeMessage) -> None:
        ...
    
    async def run_operation(self, operation: Operation[Context, RootValue]) -> None:
        """The operation task's top level method. Cleans-up and de-registers the operation once it is done."""
        ...
    
    def forget_id(self, id: str) -> None:
        ...
    
    async def handle_complete(self, message: CompleteMessage) -> None:
        ...
    
    async def handle_invalid_message(self, error_message: str) -> None:
        ...
    
    async def send_message(self, message: Message) -> None:
        ...
    
    async def cleanup_operation(self, operation_id: str) -> None:
        ...
    
    async def reap_completed_tasks(self) -> None:
        """Await tasks that have completed."""
        ...
    


class Operation(Generic[Context, RootValue]):
    """A class encapsulating a single operation with its id. Helps enforce protocol state transition."""
    __slots__ = ...
    def __init__(self, handler: BaseGraphQLTransportWSHandler[Context, RootValue], id: str, operation_type: OperationType, query: str, variables: dict[str, object] | None, operation_name: str | None) -> None:
        ...
    
    async def send_operation_message(self, message: Message) -> None:
        ...
    
    async def send_initial_errors(self, errors: list[GraphQLError]) -> None:
        ...
    
    async def send_next(self, execution_result: ExecutionResult) -> None:
        ...
    


__all__ = ["BaseGraphQLTransportWSHandler", "Operation"]
