"""
This type stub file was generated by pyright.
"""

import sys
import rich
import typer
from strawberry import Schema
from strawberry.utils.importer import import_module_symbol

def load_schema(schema: str, app_dir: str) -> Schema:
    ...

