"""
This type stub file was generated by pyright.
"""

from datetime import timedelta
from typing import Any, ClassVar, TYPE_CHECKING, TypeAlias, TypeGuard, TypedDict
from cross_web import LitestarRequestAdapter
from litestar import Controller, Request, Response, WebSocket, get, post, websocket
from litestar.exceptions import NotFoundException, ValidationException
from litestar.status_codes import HTTP_200_OK
from msgspec import Struct
from strawberry.http.async_base_view import AsyncBaseHTTPView, AsyncWebSocketAdapter
from strawberry.http.typevars import Context, RootValue
from collections.abc import AsyncGenerator, AsyncIterator, Callable, Mapping, Sequence
from litestar.types import AnyCallable, Dependencies
from strawberry.http import GraphQLHTTPResponse
from strawberry.http.ides import GraphQL_IDE
from strawberry.schema import BaseSchema

"""Litestar integration for strawberry-graphql."""
if TYPE_CHECKING:
    ...
class BaseContext(Struct, kw_only=True):
    request: Request | None = ...
    websocket: WebSocket | None = ...
    response: Response | None = ...


class HTTPContextType:
    """This class does not exists at runtime, it only set proper types for context attributes."""
    request: Request
    response: Response
    ...


class WebSocketContextType:
    """This class does not exists at runtime, it only set proper types for context attributes."""
    websocket: WebSocket
    ...


class HTTPContextDict(TypedDict):
    request: Request[Any, Any, Any]
    response: Response[Any]
    ...


class WebSocketContextDict(TypedDict):
    socket: WebSocket
    ...


MergedContext: TypeAlias = (BaseContext | WebSocketContextDict | HTTPContextDict | dict[str, Any])
class GraphQLResource(Struct):
    data: dict[str, object] | None
    errors: list[object] | None
    extensions: dict[str, object] | None
    ...


class LitestarWebSocketAdapter(AsyncWebSocketAdapter):
    def __init__(self, view: AsyncBaseHTTPView, request: WebSocket, response: WebSocket) -> None:
        ...
    
    async def iter_json(self, *, ignore_parsing_errors: bool = ...) -> AsyncGenerator[object, None]:
        ...
    
    async def send_json(self, message: Mapping[str, object]) -> None:
        ...
    
    async def close(self, code: int, reason: str) -> None:
        ...
    


class GraphQLController(Controller, AsyncBaseHTTPView[Request[Any, Any, Any], Response[Any], Response[Any], WebSocket, WebSocket, Context, RootValue,]):
    path: str = ...
    dependencies: ClassVar[Dependencies] = ...
    request_adapter_class = LitestarRequestAdapter
    websocket_adapter_class = LitestarWebSocketAdapter
    allow_queries_via_get: bool = ...
    graphiql_allowed_accept: frozenset[str] = ...
    graphql_ide: GraphQL_IDE | None = ...
    connection_init_wait_timeout: timedelta = ...
    protocols: Sequence[str] = ...
    keep_alive: bool = ...
    keep_alive_interval: float = ...
    def is_websocket_request(self, request: Request | WebSocket) -> TypeGuard[WebSocket]:
        ...
    
    async def pick_websocket_subprotocol(self, request: WebSocket) -> str | None:
        ...
    
    async def create_websocket_response(self, request: WebSocket, subprotocol: str | None) -> WebSocket:
        ...
    
    async def execute_request(self, request: Request[Any, Any, Any], context: Any, root_value: Any) -> Response[GraphQLResource | str]:
        ...
    
    async def render_graphql_ide(self, request: Request[Any, Any, Any]) -> Response[str]:
        ...
    
    def create_response(self, response_data: GraphQLHTTPResponse | list[GraphQLHTTPResponse], sub_response: Response[bytes]) -> Response[bytes]:
        ...
    
    async def create_streaming_response(self, request: Request, stream: Callable[[], AsyncIterator[str]], sub_response: Response, headers: dict[str, str]) -> Response:
        ...
    
    @get(raises=[ValidationException, NotFoundException])
    async def handle_http_get(self, request: Request[Any, Any, Any], context: Any, root_value: Any, response: Response) -> Response[GraphQLResource | str]:
        ...
    
    @post(status_code=HTTP_200_OK)
    async def handle_http_post(self, request: Request[Any, Any, Any], context: Any, root_value: Any, response: Response) -> Response[GraphQLResource | str]:
        ...
    
    @websocket()
    async def websocket_endpoint(self, socket: WebSocket, context_ws: Any, root_value: Any) -> None:
        ...
    
    async def get_context(self, request: Request[Any, Any, Any] | WebSocket, response: Response | WebSocket) -> Context:
        ...
    
    async def get_root_value(self, request: Request[Any, Any, Any] | WebSocket) -> RootValue | None:
        ...
    
    async def get_sub_response(self, request: Request[Any, Any, Any]) -> Response:
        ...
    


def make_graphql_controller(schema: BaseSchema, path: str = ..., graphiql: bool | None = ..., graphql_ide: GraphQL_IDE | None = ..., allow_queries_via_get: bool = ..., keep_alive: bool = ..., keep_alive_interval: float = ..., root_value_getter: AnyCallable | None = ..., context_getter: AnyCallable | None = ..., subscription_protocols: Sequence[str] = ..., connection_init_wait_timeout: timedelta = ..., multipart_uploads_enabled: bool = ...) -> type[GraphQLController]:
    class _GraphQLController(GraphQLController):
        ...
    
    

__all__ = ["GraphQLController", "make_graphql_controller"]
