"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, Literal
from typing_extensions import TypedDict
from strawberry.schema._graphql_core import GraphQLIncrementalExecutionResults, ResultType

class GraphQLHTTPResponse(TypedDict, total=False):
    data: dict[str, object] | None
    errors: list[object] | None
    extensions: dict[str, object] | None
    hasNext: bool | None
    completed: list[Any] | None
    pending: list[Any] | None
    initial: list[Any] | None
    incremental: list[Any] | None
    ...


def process_result(result: ResultType) -> GraphQLHTTPResponse:
    ...

@dataclass
class GraphQLRequestData:
    query: str | None
    variables: dict[str, Any] | None
    operation_name: str | None
    extensions: dict[str, Any] | None
    protocol: Literal["http", "multipart-subscription"] = ...


__all__ = ["GraphQLHTTPResponse", "GraphQLRequestData", "process_result"]
