"""
This type stub file was generated by pyright.
"""

import abc
from collections.abc import AsyncGenerator, Callable, Mapping
from datetime import timedelta
from typing import Any, Generic, TypeGuard, overload
from cross_web import AsyncHTTPRequestAdapter
from strawberry.http import GraphQLHTTPResponse, GraphQLRequestData
from strawberry.http.ides import GraphQL_IDE
from strawberry.schema.base import BaseSchema
from strawberry.subscriptions.protocols.graphql_transport_ws.handlers import BaseGraphQLTransportWSHandler
from strawberry.subscriptions.protocols.graphql_ws.handlers import BaseGraphQLWSHandler
from strawberry.types import ExecutionResult, SubscriptionExecutionResult
from strawberry.types.unset import UnsetType
from .base import BaseView
from .typevars import Context, Request, Response, RootValue, SubResponse, WebSocketRequest, WebSocketResponse

class AsyncWebSocketAdapter(abc.ABC):
    def __init__(self, view: AsyncBaseHTTPView) -> None:
        ...
    
    @abc.abstractmethod
    def iter_json(self, *, ignore_parsing_errors: bool = ...) -> AsyncGenerator[object, None]:
        ...
    
    @abc.abstractmethod
    async def send_json(self, message: Mapping[str, object]) -> None:
        ...
    
    @abc.abstractmethod
    async def close(self, code: int, reason: str) -> None:
        ...
    


class AsyncBaseHTTPView(abc.ABC, BaseView[Request], Generic[Request, Response, SubResponse, WebSocketRequest, WebSocketResponse, Context, RootValue,]):
    schema: BaseSchema
    graphql_ide: GraphQL_IDE | None
    keep_alive = ...
    keep_alive_interval: float | None = ...
    connection_init_wait_timeout: timedelta = ...
    request_adapter_class: Callable[[Request], AsyncHTTPRequestAdapter]
    websocket_adapter_class: Callable[[AsyncBaseHTTPView[Any, Any, Any, Any, Any, Context, RootValue], WebSocketRequest, WebSocketResponse], AsyncWebSocketAdapter,]
    graphql_transport_ws_handler_class: type[BaseGraphQLTransportWSHandler[Context, RootValue]] = ...
    graphql_ws_handler_class: type[BaseGraphQLWSHandler[Context, RootValue]] = ...
    @property
    @abc.abstractmethod
    def allow_queries_via_get(self) -> bool:
        ...
    
    @abc.abstractmethod
    async def get_sub_response(self, request: Request) -> SubResponse:
        ...
    
    @abc.abstractmethod
    async def get_context(self, request: Request | WebSocketRequest, response: SubResponse | WebSocketResponse) -> Context:
        ...
    
    @abc.abstractmethod
    async def get_root_value(self, request: Request | WebSocketRequest) -> RootValue | None:
        ...
    
    @abc.abstractmethod
    def create_response(self, response_data: GraphQLHTTPResponse | list[GraphQLHTTPResponse], sub_response: SubResponse) -> Response:
        ...
    
    @abc.abstractmethod
    async def render_graphql_ide(self, request: Request) -> Response:
        ...
    
    async def create_streaming_response(self, request: Request, stream: Callable[[], AsyncGenerator[str, None]], sub_response: SubResponse, headers: dict[str, str]) -> Response:
        ...
    
    @abc.abstractmethod
    def is_websocket_request(self, request: Request | WebSocketRequest) -> TypeGuard[WebSocketRequest]:
        ...
    
    @abc.abstractmethod
    async def pick_websocket_subprotocol(self, request: WebSocketRequest) -> str | None:
        ...
    
    @abc.abstractmethod
    async def create_websocket_response(self, request: WebSocketRequest, subprotocol: str | None) -> WebSocketResponse:
        ...
    
    async def execute_operation(self, request: Request, context: Context, root_value: RootValue | None, sub_response: SubResponse) -> ExecutionResult | list[ExecutionResult] | SubscriptionExecutionResult:
        ...
    
    async def execute_single(self, request: Request, request_adapter: AsyncHTTPRequestAdapter, sub_response: SubResponse, context: Context, root_value: RootValue | None, request_data: GraphQLRequestData) -> ExecutionResult:
        ...
    
    async def parse_multipart(self, request: AsyncHTTPRequestAdapter) -> dict[str, str]:
        ...
    
    @overload
    async def run(self, request: Request, context: Context = ..., root_value: RootValue | None = ...) -> Response:
        ...
    
    @overload
    async def run(self, request: WebSocketRequest, context: Context = ..., root_value: RootValue | None = ...) -> WebSocketResponse:
        ...
    
    async def run(self, request: Request | WebSocketRequest, context: Context = ..., root_value: RootValue | None = ...) -> Response | WebSocketResponse:
        ...
    
    def encode_multipart_data(self, data: Any, separator: str) -> str:
        ...
    
    async def parse_multipart_subscriptions(self, request: AsyncHTTPRequestAdapter) -> dict[str, str]:
        ...
    
    async def parse_http_body(self, request: AsyncHTTPRequestAdapter) -> GraphQLRequestData | list[GraphQLRequestData]:
        ...
    
    async def process_result(self, request: Request, result: ExecutionResult) -> GraphQLHTTPResponse:
        ...
    
    async def on_ws_connect(self, context: Context) -> UnsetType | None | dict[str, object]:
        ...
    


__all__ = ["AsyncBaseHTTPView"]
