"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from typing import Any, Generic
from typing_extensions import Protocol
from strawberry.http.ides import GraphQL_IDE
from strawberry.http.types import HTTPMethod, QueryParams
from strawberry.schema.base import BaseSchema
from .typevars import Request

class BaseRequestProtocol(Protocol):
    @property
    def query_params(self) -> Mapping[str, str | list[str] | None]:
        ...
    
    @property
    def method(self) -> HTTPMethod:
        ...
    
    @property
    def headers(self) -> Mapping[str, str]:
        ...
    


class BaseView(Generic[Request]):
    graphql_ide: GraphQL_IDE | None
    multipart_uploads_enabled: bool = ...
    schema: BaseSchema
    def should_render_graphql_ide(self, request: BaseRequestProtocol) -> bool:
        ...
    
    def is_request_allowed(self, request: BaseRequestProtocol) -> bool:
        ...
    
    def parse_json(self, data: str | bytes) -> Any:
        ...
    
    def decode_json(self, data: str | bytes) -> object:
        ...
    
    def encode_json(self, data: object) -> str | bytes:
        ...
    
    def parse_query_params(self, params: QueryParams) -> dict[str, Any]:
        ...
    
    @property
    def graphql_ide_html(self) -> str:
        ...
    


__all__ = ["BaseView"]
