"""
This type stub file was generated by pyright.
"""

class NonTextMessageReceived(Exception):
    ...


class NonJsonMessageReceived(Exception):
    ...


class WebSocketDisconnected(Exception):
    ...


__all__ = ["NonJsonMessageReceived", "NonTextMessageReceived", "WebSocketDisconnected"]
