"""
This type stub file was generated by pyright.
"""

from typing import Literal

GraphQL_IDE = Literal["graphiql", "apollo-sandbox", "pathfinder"]
def get_graphql_ide_html(graphql_ide: GraphQL_IDE | None = ...) -> str:
    ...

__all__ = ["GraphQL_IDE", "get_graphql_ide_html"]
