"""
This type stub file was generated by pyright.
"""

def parse_content_type(content_type: str) -> tuple[str, dict[str, str]]:
    """Parse a content type header into a mime-type and a dictionary of parameters."""
    ...

