"""
This type stub file was generated by pyright.
"""

import abc
from collections.abc import Callable
from typing import Generic
from cross_web import SyncHTTPRequestAdapter
from strawberry.http import GraphQLHTTPResponse, GraphQLRequestData
from strawberry.http.ides import GraphQL_IDE
from strawberry.schema import BaseSchema
from strawberry.types import ExecutionResult
from .base import BaseView
from .typevars import Context, Request, Response, RootValue, SubResponse

class SyncBaseHTTPView(abc.ABC, BaseView[Request], Generic[Request, Response, SubResponse, Context, RootValue]):
    schema: BaseSchema
    graphiql: bool | None
    graphql_ide: GraphQL_IDE | None
    request_adapter_class: Callable[[Request], SyncHTTPRequestAdapter]
    @property
    @abc.abstractmethod
    def allow_queries_via_get(self) -> bool:
        ...
    
    @abc.abstractmethod
    def get_sub_response(self, request: Request) -> SubResponse:
        ...
    
    @abc.abstractmethod
    def get_context(self, request: Request, response: SubResponse) -> Context:
        ...
    
    @abc.abstractmethod
    def get_root_value(self, request: Request) -> RootValue | None:
        ...
    
    @abc.abstractmethod
    def create_response(self, response_data: GraphQLHTTPResponse | list[GraphQLHTTPResponse], sub_response: SubResponse) -> Response:
        ...
    
    @abc.abstractmethod
    def render_graphql_ide(self, request: Request) -> Response:
        ...
    
    def execute_operation(self, request: Request, context: Context, root_value: RootValue | None, sub_response: SubResponse) -> ExecutionResult | list[ExecutionResult]:
        ...
    
    def execute_single(self, request: Request, request_adapter: SyncHTTPRequestAdapter, sub_response: SubResponse, context: Context, root_value: RootValue | None, request_data: GraphQLRequestData) -> ExecutionResult:
        ...
    
    def parse_multipart(self, request: SyncHTTPRequestAdapter) -> dict[str, str]:
        ...
    
    def parse_http_body(self, request: SyncHTTPRequestAdapter) -> GraphQLRequestData | list[GraphQLRequestData]:
        ...
    
    def run(self, request: Request, context: Context = ..., root_value: RootValue | None = ...) -> Response:
        ...
    
    def process_result(self, request: Request, result: ExecutionResult) -> GraphQLHTTPResponse:
        ...
    


__all__ = ["SyncBaseHTTPView"]
