"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

@dataclass
class TemporalResponse:
    status_code: int = ...
    headers: dict[str, str] = ...


__all__ = ["TemporalResponse"]
