"""
This type stub file was generated by pyright.
"""

import dataclasses
import keyword
import libcst as cst
from collections import defaultdict
from graphlib import TopologicalSorter
from typing import TYPE_CHECKING, TypeAlias
from typing_extensions import Protocol
from graphql import EnumTypeDefinitionNode, EnumValueDefinitionNode, FieldDefinitionNode, InputObjectTypeDefinitionNode, InputValueDefinitionNode, InterfaceTypeDefinitionNode, ListTypeNode, NamedTypeNode, NonNullTypeNode, ObjectTypeDefinitionNode, ObjectTypeExtensionNode, OperationType, ScalarTypeDefinitionNode, SchemaDefinitionNode, SchemaExtensionNode, StringValueNode, TypeNode, UnionTypeDefinitionNode, parse
from graphql.language.ast import BooleanValueNode, ConstDirectiveNode, ConstValueNode, EnumValueNode, FloatValueNode, IntValueNode, ListValueNode, NullValueNode
from strawberry.utils.str_converters import to_snake_case

if TYPE_CHECKING:
    ...
class HasDirectives(Protocol):
    directives: tuple[ConstDirectiveNode, ...]
    ...


_SCALAR_MAP = ...
@dataclasses.dataclass(frozen=True)
class Import:
    module: str | None
    imports: tuple[str]
    def module_path_to_cst(self, module_path: str) -> cst.Name | cst.Attribute:
        ...
    
    def to_cst(self) -> cst.Import | cst.ImportFrom:
        ...
    


ArgumentValue: TypeAlias = str | bool | list["ArgumentValue"]
@dataclasses.dataclass(frozen=True)
class Definition:
    code: cst.CSTNode
    dependencies: list[str]
    name: str
    ...


def codegen(schema: str) -> str:
    ...

__all__ = ["codegen"]
