"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from strawberry.types.field import StrawberryField

def create_type(name: str, fields: list[StrawberryField], is_input: bool = ..., is_interface: bool = ..., description: str | None = ..., directives: Sequence[object] | None = ..., extend: bool = ...) -> type:
    """Create a Strawberry type from a list of StrawberryFields.

    Args:
        name: The GraphQL name of the type.
        fields: The fields of the type.
        is_input: Whether the type is an input type.
        is_interface: Whether the type is an interface.
        description: The GraphQL description of the type.
        directives: The directives to attach to the type.
        extend: Whether the type is an extension.

    Example usage:

    ```python
    import strawberry


    @strawberry.field
    def hello(info) -> str:
        return "World"


    Query = create_type(name="Query", fields=[hello])
    ```
    """
    ...

__all__ = ["create_type"]
