"""
This type stub file was generated by pyright.
"""

def merge_types(name: str, types: tuple[type, ...]) -> type:
    """Merge multiple Strawberry types into one.

    For example, given two queries `A` and `B`, one can merge them into a
    super type as follows:

        merge_types("SuperQuery", (B, A))

    This is essentially the same as:

        class SuperQuery(B, A):
            ...
    """
    ...

__all__ = ["merge_types"]
