"""
This type stub file was generated by pyright.
"""

import contextlib
from collections.abc import AsyncGenerator, Awaitable, Callable, Sequence
from typing import Any, Literal
from typing_extensions import Protocol, TypedDict
from channels.consumer import AsyncConsumer
from channels.generic.websocket import AsyncWebsocketConsumer

class ChannelsMessage(TypedDict, total=False):
    type: str
    ...


class ChannelsLayer(Protocol):
    """Channels layer spec.

    Based on: https://channels.readthedocs.io/en/stable/channel_layer_spec.html
    """
    extensions: list[Literal["groups", "flush"]]
    async def send(self, channel: str, message: dict) -> None:
        ...
    
    async def receive(self, channel: str) -> dict:
        ...
    
    async def new_channel(self, prefix: str = ...) -> str:
        ...
    
    group_expiry: int
    async def group_add(self, group: str, channel: str) -> None:
        ...
    
    async def group_discard(self, group: str, channel: str) -> None:
        ...
    
    async def group_send(self, group: str, message: dict) -> None:
        ...
    
    async def flush(self) -> None:
        ...
    


class ChannelsConsumer(AsyncConsumer):
    """Base channels async consumer."""
    channel_name: str
    channel_layer: ChannelsLayer | None
    channel_receive: Callable[[], Awaitable[dict]]
    def __init__(self, *args: str, **kwargs: Any) -> None:
        ...
    
    async def dispatch(self, message: ChannelsMessage) -> None:
        ...
    
    async def channel_listen(self, type: str, *, timeout: float | None = ..., groups: Sequence[str] = ...) -> AsyncGenerator[Any, None]:
        """Listen for messages sent to this consumer.

        Utility to listen for channels messages for this consumer inside
        a resolver (usually inside a subscription).

        Args:
            type:
                The type of the message to wait for.
            timeout:
                An optional timeout to wait for each subsequent message
            groups:
                An optional sequence of groups to receive messages from.
                When passing this parameter, the groups will be registered
                using `self.channel_layer.group_add` at the beggining of the
                execution and then discarded using `self.channel_layer.group_discard`
                at the end of the execution.
        """
        ...
    
    @contextlib.asynccontextmanager
    async def listen_to_channel(self, type: str, *, timeout: float | None = ..., groups: Sequence[str] = ...) -> AsyncGenerator[Any, None]:
        """Listen for messages sent to this consumer.

        Utility to listen for channels messages for this consumer inside
        a resolver (usually inside a subscription).

        Args:
            type:
                The type of the message to wait for.
            timeout:
                An optional timeout to wait for each subsequent message
            groups:
                An optional sequence of groups to receive messages from.
                When passing this parameter, the groups will be registered
                using `self.channel_layer.group_add` at the beggining of the
                execution and then discarded using `self.channel_layer.group_discard`
                at the end of the execution.
        """
        ...
    


class ChannelsWSConsumer(ChannelsConsumer, AsyncWebsocketConsumer):
    """Base channels websocket async consumer."""
    ...


__all__ = ["ChannelsConsumer", "ChannelsWSConsumer"]
