"""
This type stub file was generated by pyright.
"""

import dataclasses
from functools import cached_property
from typing import Any, TYPE_CHECKING, TypeGuard
from channels.db import database_sync_to_async
from channels.generic.http import AsyncHttpConsumer
from cross_web import AsyncHTTPRequestAdapter, FormData, SyncHTTPRequestAdapter
from strawberry.http.async_base_view import AsyncBaseHTTPView
from strawberry.http.sync_base_view import SyncBaseHTTPView
from strawberry.http.temporal_response import TemporalResponse
from strawberry.http.typevars import Context, RootValue
from .base import ChannelsConsumer
from collections.abc import AsyncGenerator, Callable, Mapping
from strawberry.http import GraphQLHTTPResponse
from strawberry.http.ides import GraphQL_IDE
from strawberry.http.types import HTTPMethod, QueryParams
from strawberry.schema import BaseSchema

if TYPE_CHECKING:
    ...
@dataclasses.dataclass
class ChannelsResponse:
    content: bytes
    status: int = ...
    content_type: str = ...
    headers: dict[bytes, bytes] = ...


@dataclasses.dataclass
class MultipartChannelsResponse:
    stream: Callable[[], AsyncGenerator[str, None]]
    status: int = ...
    content_type: str = ...
    headers: dict[bytes, bytes] = ...


@dataclasses.dataclass
class ChannelsRequest:
    consumer: ChannelsConsumer
    body: bytes
    @property
    def query_params(self) -> QueryParams:
        ...
    
    @property
    def headers(self) -> Mapping[str, str]:
        ...
    
    @property
    def method(self) -> HTTPMethod:
        ...
    
    @property
    def content_type(self) -> str | None:
        ...
    
    @cached_property
    def form_data(self) -> FormData:
        ...
    


class BaseChannelsRequestAdapter:
    def __init__(self, request: ChannelsRequest) -> None:
        ...
    
    @property
    def query_params(self) -> QueryParams:
        ...
    
    @property
    def method(self) -> HTTPMethod:
        ...
    
    @property
    def headers(self) -> Mapping[str, str]:
        ...
    
    @property
    def content_type(self) -> str | None:
        ...
    
    @property
    def url(self) -> str:
        ...
    
    @property
    def cookies(self) -> Mapping[str, str]:
        ...
    


class ChannelsRequestAdapter(BaseChannelsRequestAdapter, AsyncHTTPRequestAdapter):
    async def get_body(self) -> bytes:
        ...
    
    async def get_form_data(self) -> FormData:
        ...
    


class SyncChannelsRequestAdapter(BaseChannelsRequestAdapter, SyncHTTPRequestAdapter):
    @property
    def body(self) -> bytes:
        ...
    
    @property
    def post_data(self) -> Mapping[str, str | bytes]:
        ...
    
    @property
    def files(self) -> Mapping[str, Any]:
        ...
    
    def get_form_data(self) -> FormData:
        ...
    


class BaseGraphQLHTTPConsumer(ChannelsConsumer, AsyncHttpConsumer):
    graphql_ide_html: str
    graphql_ide: GraphQL_IDE | None = ...
    def __init__(self, schema: BaseSchema, graphiql: bool | None = ..., graphql_ide: GraphQL_IDE | None = ..., allow_queries_via_get: bool = ..., multipart_uploads_enabled: bool = ..., **kwargs: Any) -> None:
        ...
    
    def create_response(self, response_data: GraphQLHTTPResponse | list[GraphQLHTTPResponse], sub_response: TemporalResponse) -> ChannelsResponse:
        ...
    
    async def handle(self, body: bytes) -> None:
        ...
    


class GraphQLHTTPConsumer(BaseGraphQLHTTPConsumer, AsyncBaseHTTPView[ChannelsRequest, ChannelsResponse | MultipartChannelsResponse, TemporalResponse, ChannelsRequest, TemporalResponse, Context, RootValue,]):
    """A consumer to provide a view for GraphQL over HTTP.

    To use this, place it in your ProtocolTypeRouter for your channels project:

    ```
    from strawberry.channels import GraphQLHttpRouter
    from channels.routing import ProtocolTypeRouter
    from django.core.asgi import get_asgi_application

    application = ProtocolTypeRouter({
        "http": URLRouter([
            re_path("^graphql", GraphQLHTTPRouter(schema=schema)),
            re_path("^", get_asgi_application()),
        ]),
        "websocket": URLRouter([
            re_path("^ws/graphql", GraphQLWebSocketRouter(schema=schema)),
        ]),
    })
    ```
    """
    allow_queries_via_get: bool = ...
    request_adapter_class = ChannelsRequestAdapter
    async def get_root_value(self, request: ChannelsRequest) -> RootValue | None:
        ...
    
    async def get_context(self, request: ChannelsRequest, response: TemporalResponse) -> Context:
        ...
    
    async def get_sub_response(self, request: ChannelsRequest) -> TemporalResponse:
        ...
    
    async def create_streaming_response(self, request: ChannelsRequest, stream: Callable[[], AsyncGenerator[str, None]], sub_response: TemporalResponse, headers: dict[str, str]) -> MultipartChannelsResponse:
        ...
    
    async def render_graphql_ide(self, request: ChannelsRequest) -> ChannelsResponse:
        ...
    
    def is_websocket_request(self, request: ChannelsRequest) -> TypeGuard[ChannelsRequest]:
        ...
    
    async def pick_websocket_subprotocol(self, request: ChannelsRequest) -> str | None:
        ...
    
    async def create_websocket_response(self, request: ChannelsRequest, subprotocol: str | None) -> TemporalResponse:
        ...
    


class SyncGraphQLHTTPConsumer(BaseGraphQLHTTPConsumer, SyncBaseHTTPView[ChannelsRequest, ChannelsResponse, TemporalResponse, Context, RootValue,]):
    """Synchronous version of the HTTPConsumer.

    This is the same as `GraphQLHTTPConsumer`, but it can be used with
    synchronous schemas (i.e. the schema's resolvers are expected to be
    synchronous and not asynchronous).
    """
    allow_queries_via_get: bool = ...
    request_adapter_class = SyncChannelsRequestAdapter
    def get_root_value(self, request: ChannelsRequest) -> RootValue | None:
        ...
    
    def get_context(self, request: ChannelsRequest, response: TemporalResponse) -> Context:
        ...
    
    def get_sub_response(self, request: ChannelsRequest) -> TemporalResponse:
        ...
    
    def render_graphql_ide(self, request: ChannelsRequest) -> ChannelsResponse:
        ...
    
    @database_sync_to_async
    def run(self, request: ChannelsRequest, context: Context = ..., root_value: RootValue | None = ...) -> ChannelsResponse | MultipartChannelsResponse:
        ...
    


__all__ = ["GraphQLHTTPConsumer", "SyncGraphQLHTTPConsumer"]
