"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable
from typing import Any
from strawberry.types.arguments import StrawberryArgumentAnnotation

def argument(description: str | None = ..., name: str | None = ..., deprecation_reason: str | None = ..., directives: Iterable[object] = ..., inaccessible: bool = ..., tags: Iterable[str] | None = ..., graphql_type: Any | None = ...) -> StrawberryArgumentAnnotation:
    ...

__all__ = ["argument"]
