"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING, overload
from collections.abc import Callable, Iterable
from strawberry.enum import EnumType, EnumValueDefinition

if TYPE_CHECKING:
    ...
def enum_value(value: Any, name: str | None = ..., deprecation_reason: str | None = ..., directives: Iterable[object] = ..., inaccessible: bool = ..., tags: Iterable[str] = ...) -> EnumValueDefinition:
    ...

@overload
def enum(_cls: EnumType, *, name: str | None = ..., description: str | None = ..., directives: Iterable[object] = ..., authenticated: bool = ..., inaccessible: bool = ..., policy: list[list[str]] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] | None = ...) -> EnumType:
    ...

@overload
def enum(_cls: None = ..., *, name: str | None = ..., description: str | None = ..., directives: Iterable[object] = ..., authenticated: bool = ..., inaccessible: bool = ..., policy: list[list[str]] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] | None = ...) -> Callable[[EnumType], EnumType]:
    ...

def enum(_cls: EnumType | None = ..., *, name=..., description=..., directives=..., authenticated: bool = ..., inaccessible: bool = ..., policy: list[list[str]] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] | None = ...) -> EnumType | Callable[[EnumType], EnumType]:
    """Registers the enum in the GraphQL type system.

    If name is passed, the name of the GraphQL type will be
    the value passed of name instead of the Enum class name.
    """
    ...

__all__ = ["enum", "enum_value"]
