"""
This type stub file was generated by pyright.
"""

from typing import Any, Literal, TYPE_CHECKING, TypeVar, overload
from strawberry.types.field import StrawberryField, _RESOLVER_TYPE, _RESOLVER_TYPE_ASYNC, _RESOLVER_TYPE_SYNC
from collections.abc import Callable, Iterable, Mapping, Sequence
from strawberry.extensions.field_extension import FieldExtension
from strawberry.permission import BasePermission
from .schema_directives import Override

if TYPE_CHECKING:
    ...
T = TypeVar("T")
@overload
def field(*, resolver: _RESOLVER_TYPE_ASYNC[T], name: str | None = ..., is_subscription: bool = ..., description: str | None = ..., authenticated: bool = ..., external: bool = ..., inaccessible: bool = ..., policy: list[list[str]] | None = ..., provides: list[str] | None = ..., override: Override | str | None = ..., requires: list[str] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] | None = ..., shareable: bool = ..., init: Literal[False] = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> T:
    ...

@overload
def field(*, resolver: _RESOLVER_TYPE_SYNC[T], name: str | None = ..., is_subscription: bool = ..., description: str | None = ..., authenticated: bool = ..., external: bool = ..., inaccessible: bool = ..., policy: list[list[str]] | None = ..., provides: list[str] | None = ..., override: Override | str | None = ..., requires: list[str] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] | None = ..., shareable: bool = ..., init: Literal[False] = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> T:
    ...

@overload
def field(*, name: str | None = ..., is_subscription: bool = ..., description: str | None = ..., authenticated: bool = ..., external: bool = ..., inaccessible: bool = ..., policy: list[list[str]] | None = ..., provides: list[str] | None = ..., override: Override | str | None = ..., requires: list[str] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] | None = ..., shareable: bool = ..., init: Literal[True] = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> Any:
    ...

@overload
def field(resolver: _RESOLVER_TYPE_ASYNC[T], *, name: str | None = ..., is_subscription: bool = ..., description: str | None = ..., authenticated: bool = ..., external: bool = ..., inaccessible: bool = ..., policy: list[list[str]] | None = ..., provides: list[str] | None = ..., override: Override | str | None = ..., requires: list[str] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] | None = ..., shareable: bool = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> StrawberryField:
    ...

@overload
def field(resolver: _RESOLVER_TYPE_SYNC[T], *, name: str | None = ..., is_subscription: bool = ..., description: str | None = ..., authenticated: bool = ..., external: bool = ..., inaccessible: bool = ..., policy: list[list[str]] | None = ..., provides: list[str] | None = ..., override: Override | str | None = ..., requires: list[str] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] | None = ..., shareable: bool = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> StrawberryField:
    ...

def field(resolver: _RESOLVER_TYPE[Any] | None = ..., *, name: str | None = ..., is_subscription: bool = ..., description: str | None = ..., authenticated: bool = ..., external: bool = ..., inaccessible: bool = ..., policy: list[list[str]] | None = ..., provides: list[str] | None = ..., override: Override | str | None = ..., requires: list[str] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] | None = ..., shareable: bool = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ..., init: Literal[True, False] | None = ...) -> Any:
    ...

__all__ = ["field"]
