"""
This type stub file was generated by pyright.
"""

import builtins
from collections.abc import Callable, Iterable, Sequence
from typing import TYPE_CHECKING, TypeVar, Union, overload
from typing_extensions import dataclass_transform
from strawberry.types.field import StrawberryField, field as base_field
from .field import field
from .schema_directives import Key

if TYPE_CHECKING:
    ...
T = TypeVar("T", bound=builtins.type)
@overload
@dataclass_transform(order_default=True, kw_only_default=True, field_specifiers=(base_field, field, StrawberryField))
def type(cls: T, *, name: str | None = ..., description: str | None = ..., directives: Iterable[object] = ..., authenticated: bool = ..., extend: bool = ..., inaccessible: bool = ..., keys: Iterable[Union[Key, str]] = ..., policy: list[list[str]] | None = ..., requires_scopes: list[list[str]] | None = ..., shareable: bool = ..., tags: Iterable[str] = ...) -> T:
    ...

@overload
@dataclass_transform(order_default=True, kw_only_default=True, field_specifiers=(base_field, field, StrawberryField))
def type(*, name: str | None = ..., description: str | None = ..., directives: Iterable[object] = ..., authenticated: bool = ..., extend: bool = ..., inaccessible: bool = ..., keys: Iterable[Union[Key, str]] = ..., policy: list[list[str]] | None = ..., requires_scopes: list[list[str]] | None = ..., shareable: bool = ..., tags: Iterable[str] = ...) -> Callable[[T], T]:
    ...

def type(cls: T | None = ..., *, name: str | None = ..., description: str | None = ..., directives: Iterable[object] = ..., authenticated: bool = ..., extend: bool = ..., inaccessible: bool = ..., keys: Iterable[Union[Key, str]] = ..., policy: list[list[str]] | None = ..., requires_scopes: list[list[str]] | None = ..., shareable: bool = ..., tags: Iterable[str] = ...): # -> T:
    ...

@overload
@dataclass_transform(order_default=True, kw_only_default=True, field_specifiers=(base_field, field, StrawberryField))
def input(cls: T, *, name: str | None = ..., one_of: bool | None = ..., description: str | None = ..., directives: Sequence[object] = ..., inaccessible: bool = ..., tags: Iterable[str] = ...) -> T:
    ...

@overload
@dataclass_transform(order_default=True, kw_only_default=True, field_specifiers=(base_field, field, StrawberryField))
def input(*, name: str | None = ..., description: str | None = ..., one_of: bool | None = ..., directives: Sequence[object] = ..., inaccessible: bool = ..., tags: Iterable[str] = ...) -> Callable[[T], T]:
    ...

def input(cls: T | None = ..., *, name: str | None = ..., one_of: bool | None = ..., description: str | None = ..., directives: Sequence[object] = ..., inaccessible: bool = ..., tags: Iterable[str] = ...): # -> T:
    ...

@overload
@dataclass_transform(order_default=True, kw_only_default=True, field_specifiers=(base_field, field, StrawberryField))
def interface(cls: T, *, name: str | None = ..., description: str | None = ..., directives: Iterable[object] = ..., authenticated: bool = ..., inaccessible: bool = ..., keys: Iterable[Union[Key, str]] = ..., policy: list[list[str]] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] = ...) -> T:
    ...

@overload
@dataclass_transform(order_default=True, kw_only_default=True, field_specifiers=(base_field, field, StrawberryField))
def interface(*, name: str | None = ..., description: str | None = ..., directives: Iterable[object] = ..., authenticated: bool = ..., inaccessible: bool = ..., keys: Iterable[Union[Key, str]] = ..., policy: list[list[str]] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] = ...) -> Callable[[T], T]:
    ...

def interface(cls: T | None = ..., *, name: str | None = ..., description: str | None = ..., directives: Iterable[object] = ..., authenticated: bool = ..., inaccessible: bool = ..., keys: Iterable[Union[Key, str]] = ..., policy: list[list[str]] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] = ...): # -> T:
    ...

@overload
@dataclass_transform(order_default=True, kw_only_default=True, field_specifiers=(base_field, field, StrawberryField))
def interface_object(cls: T, *, name: str | None = ..., description: str | None = ..., directives: Iterable[object] = ..., authenticated: bool = ..., inaccessible: bool = ..., keys: Iterable[Union[Key, str]] = ..., policy: list[list[str]] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] = ...) -> T:
    ...

@overload
@dataclass_transform(order_default=True, kw_only_default=True, field_specifiers=(base_field, field, StrawberryField))
def interface_object(*, name: str | None = ..., description: str | None = ..., directives: Iterable[object] = ..., authenticated: bool = ..., inaccessible: bool = ..., keys: Iterable[Union[Key, str]] = ..., policy: list[list[str]] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] = ...) -> Callable[[T], T]:
    ...

def interface_object(cls: T | None = ..., *, name: str | None = ..., description: str | None = ..., directives: Iterable[object] = ..., authenticated: bool = ..., inaccessible: bool = ..., keys: Iterable[Union[Key, str]] = ..., policy: list[list[str]] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] = ...): # -> T:
    ...

__all__ = ["input", "interface", "interface_object", "type"]
