"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Iterable
from typing import Any, NewType, TypeVar, overload

_T = TypeVar("_T", bound=type | NewType)
def identity(x: _T) -> _T:
    ...

@overload
def scalar(*, name: str | None = ..., description: str | None = ..., specified_by_url: str | None = ..., serialize: Callable = ..., parse_value: Callable | None = ..., parse_literal: Callable | None = ..., directives: Iterable[object] = ..., authenticated: bool = ..., inaccessible: bool = ..., policy: list[list[str]] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] | None = ...) -> Callable[[_T], _T]:
    ...

@overload
def scalar(cls: _T, *, name: str | None = ..., description: str | None = ..., specified_by_url: str | None = ..., serialize: Callable = ..., parse_value: Callable | None = ..., parse_literal: Callable | None = ..., directives: Iterable[object] = ..., authenticated: bool = ..., inaccessible: bool = ..., policy: list[list[str]] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] | None = ...) -> _T:
    ...

def scalar(cls: _T | None = ..., *, name: str | None = ..., description: str | None = ..., specified_by_url: str | None = ..., serialize: Callable = ..., parse_value: Callable | None = ..., parse_literal: Callable | None = ..., directives: Iterable[object] = ..., authenticated: bool = ..., inaccessible: bool = ..., policy: list[list[str]] | None = ..., requires_scopes: list[list[str]] | None = ..., tags: Iterable[str] | None = ...) -> Any:
    """Annotates a class or type as a GraphQL custom scalar.

    Args:
        cls: The class or type to annotate
        name: The GraphQL name of the scalar
        description: The description of the scalar
        specified_by_url: The URL of the specification
        serialize: The function to serialize the scalar
        parse_value: The function to parse the value
        parse_literal: The function to parse the literal
        directives: The directives to apply to the scalar
        authenticated: Whether to add the @authenticated directive
        inaccessible: Whether to add the @inaccessible directive
        policy: The list of policy names to add to the @policy directive
        requires_scopes: The list of scopes to add to the @requires directive
        tags: The list of tags to add to the @tag directive

    Returns:
        The decorated class or type

    Example usages:

    ```python
    strawberry.federation.scalar(
        datetime.date,
        serialize=lambda value: value.isoformat(),
        parse_value=datetime.parse_date,
    )

    Base64Encoded = strawberry.federation.scalar(
        NewType("Base64Encoded", bytes),
        serialize=base64.b64encode,
        parse_value=base64.b64decode,
    )


    @strawberry.federation.scalar(
        serialize=lambda value: ",".join(value.items),
        parse_value=lambda value: CustomList(value.split(",")),
    )
    class CustomList:
        def __init__(self, items):
            self.items = items
    ```
    """
    ...

__all__ = ["scalar"]
