"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable
from functools import cached_property
from typing import Literal, NewType, Optional, TYPE_CHECKING, Union
from strawberry.schema import Schema as BaseSchema
from strawberry.types.info import Info
from strawberry.types.scalar import ScalarDefinition, ScalarWrapper
from graphql import ExecutionContext as GraphQLExecutionContext
from strawberry.extensions import SchemaExtension
from strawberry.schema.config import StrawberryConfig

if TYPE_CHECKING:
    ...
FederationAny = NewType("FederationAny", object)
class Schema(BaseSchema):
    def __init__(self, query: type | None = ..., mutation: type | None = ..., subscription: type | None = ..., directives: Iterable[type] = ..., types: Iterable[type] = ..., extensions: Iterable[Union[type[SchemaExtension], SchemaExtension]] = ..., execution_context_class: type[GraphQLExecutionContext] | None = ..., config: Optional[StrawberryConfig] = ..., scalar_overrides: dict[object, Union[type, ScalarWrapper, ScalarDefinition]] | None = ..., schema_directives: Iterable[object] = ..., federation_version: Literal["2.0", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7", "2.8", "2.9", "2.10", "2.11",] = ...) -> None:
        ...
    
    def entities_resolver(self, info: Info, representations: list[FederationAny]) -> list[FederationAny]:
        ...
    
    @cached_property
    def schema_directives_in_use(self) -> list[object]:
        ...
    


__all__ = ["Schema"]
