"""
This type stub file was generated by pyright.
"""

import dataclasses
from collections.abc import Callable
from typing import TypeVar
from typing_extensions import dataclass_transform
from strawberry.directive import directive_field
from strawberry.schema_directive import Location, StrawberrySchemaDirective
from strawberry.types.field import StrawberryField, field

@dataclasses.dataclass
class ComposeOptions:
    import_url: str | None
    ...


@dataclasses.dataclass
class StrawberryFederationSchemaDirective(StrawberrySchemaDirective):
    compose_options: ComposeOptions | None = ...


T = TypeVar("T", bound=type)
@dataclass_transform(order_default=True, kw_only_default=True, field_specifiers=(directive_field, field, StrawberryField))
def schema_directive(*, locations: list[Location], description: str | None = ..., name: str | None = ..., repeatable: bool = ..., print_definition: bool = ..., compose: bool = ..., import_url: str | None = ...) -> Callable[[T], T]:
    ...

__all__ = ["Location", "schema_directive"]
