"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import NewType
from strawberry.types.enum import enum

FieldSet = NewType("FieldSet", str)
LinkImport = NewType("LinkImport", object)
@enum(name="link__Purpose")
class LinkPurpose(Enum):
    SECURITY = ...
    EXECUTION = ...


__all__ = ["FieldSet", "LinkImport", "LinkPurpose"]
