"""
This type stub file was generated by pyright.
"""

from collections.abc import Collection, Iterable
from typing import Any
from strawberry.types.union import StrawberryUnion

def union(name: str, types: Collection[type[Any]] | None = ..., *, description: str | None = ..., directives: Iterable[object] = ..., inaccessible: bool = ..., tags: Iterable[str] | None = ...) -> StrawberryUnion:
    """Creates a new named Union type.

    Args:
        name: The GraphQL name of the Union type.
        types: The types that the Union can be.
            (Deprecated, use `Annotated[U, strawberry.federation.union("Name")]` instead)
        description: The  GraphQL description of the Union type.
        directives: The directives to attach to the Union type.
        inaccessible: Whether the Union type is inaccessible.
        tags: The federation tags to attach to the Union type.

    Example usages:

    ```python
    import strawberry
    from typing import Annotated

    @strawberry.federation.type(keys=["id"])
    class A:
        id: strawberry.ID

    @strawberry.federation.type(keys=["id"])
    class B:
        id: strawberry.ID

    MyUnion = Annotated[A | B, strawberry.federation.union("Name", tags=["tag"])]
    """
    ...

__all__ = ["union"]
