"""
This type stub file was generated by pyright.
"""

FederationVersion = tuple[int, int]
FEDERATION_VERSIONS: dict[str, FederationVersion] = ...
def parse_version(version_str: str) -> FederationVersion:
    """Parse a version string like '2.5' into a tuple (2, 5)."""
    ...

def format_version(version: FederationVersion) -> str:
    """Format a version tuple (2, 5) into a string 'v2.5'."""
    ...

