"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from functools import cached_property
from pathlib import Path
from typing import Any, TYPE_CHECKING
from strawberry.exceptions.exception_source import ExceptionSource
from collections.abc import Callable
from inspect import Traceback
from strawberry.types.scalar import ScalarDefinition
from strawberry.types.union import StrawberryUnion

if TYPE_CHECKING:
    ...
@dataclass
class SourcePath:
    path: Path
    code: str
    ...


class LibCSTSourceFinder:
    def __init__(self) -> None:
        ...
    
    def find_source(self, module: str) -> SourcePath | None:
        ...
    
    def find_class(self, cls: type[Any]) -> ExceptionSource | None:
        ...
    
    def find_class_attribute(self, cls: type[Any], attribute_name: str) -> ExceptionSource | None:
        ...
    
    def find_function(self, function: Callable[..., Any]) -> ExceptionSource | None:
        ...
    
    def find_argument(self, function: Callable[..., Any], argument_name: str) -> ExceptionSource | None:
        ...
    
    def find_union_call(self, path: Path, union_name: str, invalid_type: object) -> ExceptionSource | None:
        ...
    
    def find_union_merge(self, union: StrawberryUnion, other: object, frame: Traceback) -> ExceptionSource | None:
        ...
    
    def find_annotated_union(self, union_definition: StrawberryUnion, invalid_type: object) -> ExceptionSource | None:
        ...
    
    def find_scalar_call(self, scalar_definition: ScalarDefinition) -> ExceptionSource | None:
        ...
    


class SourceFinder:
    @cached_property
    def cst(self) -> LibCSTSourceFinder | None:
        ...
    
    def find_class_from_object(self, cls: type[Any]) -> ExceptionSource | None:
        ...
    
    def find_class_attribute_from_object(self, cls: type[Any], attribute_name: str) -> ExceptionSource | None:
        ...
    
    def find_function_from_object(self, function: Callable[..., Any]) -> ExceptionSource | None:
        ...
    
    def find_argument_from_object(self, function: Callable[..., Any], argument_name: str) -> ExceptionSource | None:
        ...
    
    def find_union_call(self, path: Path, union_name: str, invalid_type: object) -> ExceptionSource | None:
        ...
    
    def find_union_merge(self, union: StrawberryUnion, other: object, frame: Traceback) -> ExceptionSource | None:
        ...
    
    def find_scalar_call(self, scalar_definition: ScalarDefinition) -> ExceptionSource | None:
        ...
    
    def find_annotated_union(self, union_definition: StrawberryUnion, invalid_type: object) -> ExceptionSource | None:
        ...
    


__all__ = ["SourceFinder"]
