"""
This type stub file was generated by pyright.
"""

from typing import TypeAlias, Union
from graphql.execution import ExecutionResult as OriginalGraphQLExecutionResult, InitialIncrementalExecutionResult
from strawberry.types import ExecutionResult
from graphql import ExperimentalIncrementalExecutionResults as GraphQLIncrementalExecutionResults

incremental_execution_directives = ...
GraphQLExecutionResult: TypeAlias = (OriginalGraphQLExecutionResult | InitialIncrementalExecutionResult)
ResultType = Union[OriginalGraphQLExecutionResult, GraphQLIncrementalExecutionResults, ExecutionResult,]
__all__ = ["GraphQLExecutionContext", "GraphQLExecutionResult", "GraphQLIncrementalExecutionResults", "ResultType", "execute", "experimental_execute_incrementally", "incremental_execution_directives", "subscribe"]
