"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from typing import Any, TYPE_CHECKING
from typing_extensions import Protocol
from collections.abc import Iterable
from graphql import GraphQLError
from strawberry.directive import StrawberryDirective
from strawberry.schema.schema import SubscriptionResult
from strawberry.schema.schema_converter import GraphQLCoreConverter
from strawberry.types import ExecutionContext, ExecutionResult
from strawberry.types.base import StrawberryObjectDefinition, WithStrawberryObjectDefinition
from strawberry.types.enum import StrawberryEnumDefinition
from strawberry.types.graphql import OperationType
from strawberry.types.scalar import ScalarDefinition
from strawberry.types.union import StrawberryUnion
from .config import StrawberryConfig

if TYPE_CHECKING:
    ...
class BaseSchema(Protocol):
    config: StrawberryConfig
    schema_converter: GraphQLCoreConverter
    query: type[WithStrawberryObjectDefinition]
    mutation: type[WithStrawberryObjectDefinition] | None
    subscription: type[WithStrawberryObjectDefinition] | None
    schema_directives: list[object]
    @abstractmethod
    async def execute(self, query: str | None, variable_values: dict[str, Any] | None = ..., context_value: Any | None = ..., root_value: Any | None = ..., operation_name: str | None = ..., allowed_operation_types: Iterable[OperationType] | None = ..., operation_extensions: dict[str, Any] | None = ...) -> ExecutionResult:
        ...
    
    @abstractmethod
    def execute_sync(self, query: str | None, variable_values: dict[str, Any] | None = ..., context_value: Any | None = ..., root_value: Any | None = ..., operation_name: str | None = ..., allowed_operation_types: Iterable[OperationType] | None = ..., operation_extensions: dict[str, Any] | None = ...) -> ExecutionResult:
        ...
    
    @abstractmethod
    async def subscribe(self, query: str, variable_values: dict[str, Any] | None = ..., context_value: Any | None = ..., root_value: Any | None = ..., operation_name: str | None = ..., operation_extensions: dict[str, Any] | None = ...) -> SubscriptionResult:
        ...
    
    @abstractmethod
    def get_type_by_name(self, name: str) -> (StrawberryObjectDefinition | ScalarDefinition | StrawberryEnumDefinition | StrawberryUnion | None):
        ...
    
    @abstractmethod
    def get_directive_by_name(self, graphql_name: str) -> StrawberryDirective | None:
        ...
    
    @abstractmethod
    def as_str(self) -> str:
        ...
    
    @staticmethod
    def remove_field_suggestion(error: GraphQLError) -> None:
        ...
    
    def process_errors(self, errors: list[GraphQLError], execution_context: ExecutionContext | None = ...) -> None:
        ...
    


__all__ = ["BaseSchema"]
