"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING, TypeGuard
from strawberry.types.base import StrawberryType
from collections.abc import Mapping
from strawberry.types.scalar import ScalarDefinition, ScalarWrapper

if TYPE_CHECKING:
    ...
def is_input_type(type_: StrawberryType | type) -> TypeGuard[type]:
    ...

def is_interface_type(type_: StrawberryType | type) -> TypeGuard[type]:
    ...

def is_scalar(type_: StrawberryType | type, scalar_registry: Mapping[object, ScalarWrapper | ScalarDefinition]) -> TypeGuard[type]:
    ...

def is_schema_directive(type_: StrawberryType | type) -> TypeGuard[type]:
    ...

def is_graphql_generic(type_: StrawberryType | type) -> bool:
    ...

__all__ = ["is_graphql_generic", "is_input_type", "is_interface_type", "is_scalar", "is_schema_directive"]
