"""
This type stub file was generated by pyright.
"""

from dataclasses import InitVar, dataclass
from typing import Any, TYPE_CHECKING, TypedDict
from strawberry.types.info import Info
from .name_converter import NameConverter
from collections.abc import Callable, Mapping
from strawberry.types.scalar import ScalarDefinition

if TYPE_CHECKING:
    ...
class BatchingConfig(TypedDict):
    max_operations: int
    ...


@dataclass
class StrawberryConfig:
    """Configuration for a Strawberry GraphQL schema.

    Attributes:
        auto_camel_case: Whether to automatically convert field names to camelCase.
        name_converter: The name converter to use for type/field names.
        default_resolver: The default resolver function for fields.
        relay_max_results: Maximum results for Relay connections.
        relay_use_legacy_global_id: Use legacy GlobalID format for Relay.
        disable_field_suggestions: Disable field suggestions in error messages.
        info_class: Custom Info class to use.
        enable_experimental_incremental_execution: Enable @defer/@stream support.
        scalar_map: A mapping of types to their scalar definitions. This allows
            any type (including NewType) to be used as a GraphQL scalar with
            proper type checking support.
        batching_config: Configuration for operation batching.
    """
    auto_camel_case: InitVar[bool] = ...
    name_converter: NameConverter = ...
    default_resolver: Callable[[Any, str], object] = ...
    relay_max_results: int = ...
    relay_use_legacy_global_id: bool = ...
    disable_field_suggestions: bool = ...
    info_class: type[Info] = ...
    enable_experimental_incremental_execution: bool = ...
    _unsafe_disable_same_type_validation: bool = ...
    scalar_map: Mapping[object, ScalarDefinition] = ...
    batching_config: BatchingConfig | None = ...
    def __post_init__(self, auto_camel_case: bool) -> None:
        ...
    


__all__ = ["StrawberryConfig"]
