"""
This type stub file was generated by pyright.
"""

from strawberry.types.graphql import OperationType

class CannotGetOperationTypeError(Exception):
    """Internal error raised when we cannot get the operation type from a GraphQL document."""
    def __init__(self, operation_name: str | None) -> None:
        ...
    
    def as_http_error_reason(self) -> str:
        ...
    


class InvalidOperationTypeError(Exception):
    def __init__(self, operation_type: OperationType) -> None:
        ...
    
    def as_http_error_reason(self, method: str) -> str:
        ...
    


__all__ = ["CannotGetOperationTypeError", "InvalidOperationTypeError"]
