"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from typing_extensions import Protocol
from strawberry.directive import StrawberryDirective
from strawberry.schema_directive import StrawberrySchemaDirective
from strawberry.types.base import StrawberryObjectDefinition, StrawberryType
from strawberry.types.enum import EnumValue, StrawberryEnumDefinition
from strawberry.types.scalar import ScalarDefinition
from strawberry.types.union import StrawberryUnion
from strawberry.types.arguments import StrawberryArgument
from strawberry.types.field import StrawberryField

if TYPE_CHECKING:
    ...
class HasGraphQLName(Protocol):
    python_name: str
    graphql_name: str | None
    ...


class NameConverter:
    def __init__(self, auto_camel_case: bool = ...) -> None:
        ...
    
    def apply_naming_config(self, name: str) -> str:
        ...
    
    def from_type(self, type_: StrawberryType | StrawberryDirective) -> str:
        ...
    
    def from_argument(self, argument: StrawberryArgument) -> str:
        ...
    
    def from_object(self, object_type: StrawberryObjectDefinition) -> str:
        ...
    
    def from_input_object(self, input_type: StrawberryObjectDefinition) -> str:
        ...
    
    def from_interface(self, interface: StrawberryObjectDefinition) -> str:
        ...
    
    def from_enum(self, enum: StrawberryEnumDefinition) -> str:
        ...
    
    def from_enum_value(self, enum: StrawberryEnumDefinition, enum_value: EnumValue) -> str:
        ...
    
    def from_directive(self, directive: StrawberryDirective | StrawberrySchemaDirective) -> str:
        ...
    
    def from_scalar(self, scalar: ScalarDefinition) -> str:
        ...
    
    def from_field(self, field: StrawberryField) -> str:
        ...
    
    def from_union(self, union: StrawberryUnion) -> str:
        ...
    
    def from_generic(self, generic_type: StrawberryObjectDefinition, types: list[StrawberryType | type]) -> str:
        ...
    
    def get_name_from_type(self, type_: StrawberryType | type) -> str:
        ...
    
    def get_graphql_name(self, obj: HasGraphQLName) -> str:
        ...
    


__all__ = ["NameConverter"]
