"""
This type stub file was generated by pyright.
"""

from collections.abc import AsyncGenerator, AsyncIterator, Callable, Iterable, Mapping
from functools import lru_cache
from typing import Any, NamedTuple, TYPE_CHECKING, TypeAlias
from graphql import FieldNode, FragmentDefinitionNode, GraphQLError, GraphQLField, GraphQLObjectType, GraphQLOutputType, GraphQLSchema, OperationDefinitionNode
from graphql.validation import ASTValidationRule
from strawberry.extensions import SchemaExtension
from strawberry.extensions.runner import SchemaExtensionsRunner
from strawberry.types.base import StrawberryObjectDefinition, StrawberryType
from strawberry.types.execution import ExecutionContext, ExecutionResult, PreExecutionError
from strawberry.types.graphql import OperationType
from strawberry.utils import IS_GQL_33
from ._graphql_core import GraphQLExecutionContext
from .base import BaseSchema
from .config import StrawberryConfig
from graphql.language import DocumentNode
from graphql.pyutils import Path
from graphql.type import GraphQLResolveInfo
from strawberry.directive import StrawberryDirective
from strawberry.types.enum import StrawberryEnumDefinition
from strawberry.types.field import StrawberryField
from strawberry.types.scalar import ScalarDefinition, ScalarWrapper
from strawberry.types.union import StrawberryUnion

if TYPE_CHECKING:
    ...
SubscriptionResult: TypeAlias = AsyncGenerator[PreExecutionError | ExecutionResult, None]
OriginSubscriptionResult: TypeAlias = (OriginalExecutionResult | AsyncIterator[OriginalExecutionResult])
DEFAULT_ALLOWED_OPERATION_TYPES = ...
ProcessErrors: TypeAlias = "Callable[[list[GraphQLError], ExecutionContext | None], None]"
def validate_document(schema: GraphQLSchema, document: DocumentNode, validation_rules: tuple[type[ASTValidationRule], ...]) -> list[GraphQLError]:
    ...

class _OperationContextAwareGraphQLResolveInfo(NamedTuple):
    field_name: str
    field_nodes: list[FieldNode]
    return_type: GraphQLOutputType
    parent_type: GraphQLObjectType
    path: Path
    schema: GraphQLSchema
    fragments: dict[str, FragmentDefinitionNode]
    root_value: Any
    operation: OperationDefinitionNode
    variable_values: dict[str, Any]
    context: Any
    is_awaitable: Callable[[Any], bool]
    operation_extensions: dict[str, Any]
    ...


class StrawberryGraphQLCoreExecutionContext(GraphQLExecutionContext):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    
    if IS_GQL_33:
        def build_resolve_info(self, field_def: GraphQLField, field_nodes: list[FieldNode], parent_type: GraphQLObjectType, path: Path) -> GraphQLResolveInfo:
            ...
        


class Schema(BaseSchema):
    def __init__(self, query: type, mutation: type | None = ..., subscription: type | None = ..., directives: Iterable[StrawberryDirective] = ..., types: Iterable[type | StrawberryType] = ..., extensions: Iterable[type[SchemaExtension] | SchemaExtension] = ..., execution_context_class: type[GraphQLExecutionContext] | None = ..., config: StrawberryConfig | None = ..., scalar_overrides: (Mapping[object, type | ScalarWrapper | ScalarDefinition] | None) = ..., schema_directives: Iterable[object] = ...) -> None:
        """Default Schema to be used in a Strawberry application.

        A GraphQL Schema class used to define the structure and configuration
        of GraphQL queries, mutations, and subscriptions.

        This class allows the creation of a GraphQL schema by specifying the types
        for queries, mutations, and subscriptions, along with various configuration
        options such as directives, extensions, and scalar overrides.

        Args:
            query: The entry point for queries.
            mutation: The entry point for mutations.
            subscription: The entry point for subscriptions.
            directives: A list of operation directives that clients can use.
                The bult-in `@include` and `@skip` are included by default.
            types: A list of additional types that will be included in the schema.
            extensions: A list of Strawberry extensions.
            execution_context_class: The execution context class.
            config: The configuration for the schema.
            scalar_overrides: A dictionary of overrides for scalars.
            schema_directives: A list of schema directives for the schema.

        Example:
        ```python
        import strawberry


        @strawberry.type
        class Query:
            name: str = "Patrick"


        schema = strawberry.Schema(query=Query)
        ```
        """
        ...
    
    def get_extensions(self, sync: bool = ...) -> list[SchemaExtension]:
        ...
    
    def create_extensions_runner(self, execution_context: ExecutionContext, extensions: list[SchemaExtension]) -> SchemaExtensionsRunner:
        ...
    
    @lru_cache
    def get_type_by_name(self, name: str) -> (StrawberryObjectDefinition | ScalarDefinition | StrawberryEnumDefinition | StrawberryUnion | None):
        ...
    
    def get_field_for_type(self, field_name: str, type_name: str) -> StrawberryField | None:
        ...
    
    @lru_cache
    def get_directive_by_name(self, graphql_name: str) -> StrawberryDirective | None:
        ...
    
    def get_fields(self, type_definition: StrawberryObjectDefinition) -> list[StrawberryField]:
        ...
    
    async def execute(self, query: str | None, variable_values: dict[str, Any] | None = ..., context_value: Any | None = ..., root_value: Any | None = ..., operation_name: str | None = ..., allowed_operation_types: Iterable[OperationType] | None = ..., operation_extensions: dict[str, Any] | None = ...) -> ExecutionResult:
        ...
    
    def execute_sync(self, query: str | None, variable_values: dict[str, Any] | None = ..., context_value: Any | None = ..., root_value: Any | None = ..., operation_name: str | None = ..., allowed_operation_types: Iterable[OperationType] | None = ..., operation_extensions: dict[str, Any] | None = ...) -> ExecutionResult:
        ...
    
    async def subscribe(self, query: str | None, variable_values: dict[str, Any] | None = ..., context_value: Any | None = ..., root_value: Any | None = ..., operation_name: str | None = ..., operation_extensions: dict[str, Any] | None = ...) -> SubscriptionResult:
        ...
    
    def as_str(self) -> str:
        ...
    
    __str__ = ...
    def introspect(self) -> dict[str, Any]:
        """Return the introspection query result for the current schema.

        Raises:
            ValueError: If the introspection query fails due to an invalid schema
        """
        ...
    


__all__ = ["Schema"]
