"""
This type stub file was generated by pyright.
"""

from typing import Any, Generic, TYPE_CHECKING, TypeVar
from typing_extensions import Protocol
from graphql import GraphQLArgument, GraphQLDirective, GraphQLEnumType, GraphQLEnumValue, GraphQLField, GraphQLInputField, GraphQLInputObjectType, GraphQLInterfaceType, GraphQLList, GraphQLNonNull, GraphQLNullableType, GraphQLObjectType, GraphQLScalarType, GraphQLUnionType, ValueNode
from strawberry.types.arguments import StrawberryArgument
from strawberry.types.base import StrawberryList, StrawberryObjectDefinition, StrawberryType
from strawberry.types.enum import EnumValue, StrawberryEnumDefinition
from strawberry.types.field import StrawberryField
from strawberry.types.scalar import ScalarDefinition, ScalarWrapper
from strawberry.types.union import StrawberryUnion
from .types.concrete_type import ConcreteType
from collections.abc import Callable, Mapping
from strawberry.directive import StrawberryDirective
from strawberry.schema.config import StrawberryConfig
from strawberry.types.info import Info

if TYPE_CHECKING:
    ...
FieldType = TypeVar("FieldType", bound=GraphQLField | GraphQLInputField, covariant=True)
class FieldConverterProtocol(Protocol, Generic[FieldType]):
    def __call__(self, field: StrawberryField, *, type_definition: StrawberryObjectDefinition | None = ...) -> FieldType:
        ...
    


class CustomGraphQLEnumType(GraphQLEnumType):
    def __init__(self, enum: StrawberryEnumDefinition, *args: Any, **kwargs: Any) -> None:
        ...
    
    def serialize(self, output_value: Any) -> str:
        ...
    
    def parse_value(self, input_value: str) -> Any:
        ...
    
    def parse_literal(self, value_node: ValueNode, _variables: dict[str, Any] | None = ...) -> Any:
        ...
    


def get_arguments(*, field: StrawberryField, source: Any, info: Info, kwargs: Any, config: StrawberryConfig, scalar_registry: Mapping[object, ScalarWrapper | ScalarDefinition]) -> tuple[list[Any], dict[str, Any]]:
    ...

class GraphQLCoreConverter:
    DEFINITION_BACKREF = ...
    def __init__(self, config: StrawberryConfig, scalar_overrides: Mapping[object, ScalarWrapper | ScalarDefinition], scalar_map: Mapping[object, ScalarDefinition], get_fields: Callable[[StrawberryObjectDefinition], list[StrawberryField]]) -> None:
        ...
    
    def from_argument(self, argument: StrawberryArgument) -> GraphQLArgument:
        ...
    
    def from_enum(self, enum: StrawberryEnumDefinition) -> CustomGraphQLEnumType:
        ...
    
    def from_enum_value(self, enum_value: EnumValue) -> GraphQLEnumValue:
        ...
    
    def from_directive(self, directive: StrawberryDirective) -> GraphQLDirective:
        ...
    
    def from_schema_directive(self, cls: type) -> GraphQLDirective:
        ...
    
    def from_field(self, field: StrawberryField, *, type_definition: StrawberryObjectDefinition | None = ...) -> GraphQLField:
        ...
    
    def from_input_field(self, field: StrawberryField, *, type_definition: StrawberryObjectDefinition | None = ...) -> GraphQLInputField:
        ...
    
    def get_graphql_fields(self, type_definition: StrawberryObjectDefinition) -> dict[str, GraphQLField]:
        ...
    
    def get_graphql_input_fields(self, type_definition: StrawberryObjectDefinition) -> dict[str, GraphQLInputField]:
        ...
    
    def from_input_object(self, object_type: type) -> GraphQLInputObjectType:
        ...
    
    def from_interface(self, interface: StrawberryObjectDefinition) -> GraphQLInterfaceType:
        ...
    
    def from_list(self, type_: StrawberryList) -> GraphQLList:
        ...
    
    def from_object(self, object_type: StrawberryObjectDefinition) -> GraphQLObjectType:
        ...
    
    def from_resolver(self, field: StrawberryField) -> Callable:
        ...
    
    def from_scalar(self, scalar: type) -> GraphQLScalarType:
        ...
    
    def from_maybe_optional(self, type_: StrawberryType | type) -> GraphQLNullableType | GraphQLNonNull:
        ...
    
    def from_type(self, type_: StrawberryType | type) -> GraphQLNullableType:
        ...
    
    def from_union(self, union: StrawberryUnion) -> GraphQLUnionType:
        ...
    
    def validate_same_type_definition(self, name: str, type_definition: StrawberryType, cached_type: ConcreteType) -> None:
        ...
    
    def is_same_type_definition(self, first_type_definition: StrawberryObjectDefinition | StrawberryType, second_type_definition: StrawberryObjectDefinition | StrawberryType) -> bool:
        ...
    


__all__ = ["GraphQLCoreConverter"]
