"""
This type stub file was generated by pyright.
"""

import glob
import pathlib
import sys
import rich
import typer
from libcst.codemod import CodemodContext
from strawberry.cli.app import app
from strawberry.codemods.annotated_unions import ConvertUnionToAnnotatedUnion
from strawberry.codemods.maybe_optional import ConvertMaybeToOptional
from strawberry.codemods.replace_scalar_wrappers import ReplaceScalarWrappers
from strawberry.codemods.update_imports import UpdateImportsCodemod
from ._run_codemod import run_codemod

codemods = ...
@app.command(help="Upgrades a Strawberry project to the latest version")
def upgrade(codemod: str = ..., paths: list[pathlib.Path] = ..., python_target: str = ..., use_typing_extensions: bool = ...) -> None:
    ...

