"""
This type stub file was generated by pyright.
"""

from typing import Any
from typing_extensions import Self
from rich.progress import TaskID

class FakeProgress:
    """A fake progress bar that does nothing.

    This is used when the user has only one file to process.
    """
    def advance(self, task_id: TaskID) -> None:
        ...
    
    def add_task(self, *args: Any, **kwargs: Any) -> TaskID:
        ...
    
    def __enter__(self) -> Self:
        ...
    
    def __exit__(self, *args: object, **kwargs: Any) -> None:
        ...
    


