"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING, TypeAlias
from libcst.codemod._cli import ExecutionResult
from rich.progress import Progress
from ._fake_progress import FakeProgress
from collections.abc import Generator, Sequence
from libcst.codemod import Codemod

if TYPE_CHECKING:
    ...
ProgressType: TypeAlias = type[Progress] | type[FakeProgress]
def run_codemod(codemod: Codemod, files: Sequence[str]) -> Generator[ExecutionResult, None, None]:
    ...

