"""
This type stub file was generated by pyright.
"""

from functools import cached_property
from typing import TYPE_CHECKING
from graphql import GraphQLError, GraphQLInputObjectType, GraphQLObjectType
from .conflicting_arguments import ConflictingArgumentsError
from .duplicated_type_name import DuplicatedTypeName
from .exception import StrawberryException, UnableToFindExceptionSource
from .handler import setup_exception_handler
from .invalid_argument_type import InvalidArgumentTypeError
from .invalid_superclass_interface import InvalidSuperclassInterfaceError
from .invalid_union_type import InvalidTypeForUnionMergeError, InvalidUnionTypeError
from .missing_arguments_annotations import MissingArgumentsAnnotationsError
from .missing_dependencies import MissingOptionalDependenciesError
from .missing_field_annotation import MissingFieldAnnotationError
from .missing_return_annotation import MissingReturnAnnotationError
from .object_is_not_a_class import ObjectIsNotClassError
from .object_is_not_an_enum import ObjectIsNotAnEnumError
from .private_strawberry_field import PrivateStrawberryFieldError
from .scalar_already_registered import ScalarAlreadyRegisteredError
from .unresolved_field_type import UnresolvedFieldTypeError
from strawberry.types.base import StrawberryType
from .exception_source import ExceptionSource

if TYPE_CHECKING:
    ...
class WrongReturnTypeForUnion(Exception):
    """The Union type cannot be resolved because it's not a field."""
    def __init__(self, field_name: str, result_type: str) -> None:
        ...
    


class UnallowedReturnTypeForUnion(Exception):
    """The return type is not in the list of Union types."""
    def __init__(self, field_name: str, result_type: str, allowed_types: set[GraphQLObjectType]) -> None:
        ...
    


class InvalidTypeInputForUnion(Exception):
    def __init__(self, annotation: GraphQLInputObjectType) -> None:
        ...
    


class MissingTypesForGenericError(Exception):
    """Raised when a generic types was used without passing any type."""
    def __init__(self, annotation: StrawberryType | type) -> None:
        ...
    


class UnsupportedTypeError(StrawberryException):
    def __init__(self, annotation: StrawberryType | type) -> None:
        ...
    
    @cached_property
    def exception_source(self) -> ExceptionSource | None:
        ...
    


class MultipleStrawberryArgumentsError(Exception):
    def __init__(self, argument_name: str) -> None:
        ...
    


class WrongNumberOfResultsReturned(Exception):
    def __init__(self, expected: int, received: int) -> None:
        ...
    


class FieldWithResolverAndDefaultValueError(Exception):
    def __init__(self, field_name: str, type_name: str) -> None:
        ...
    


class FieldWithResolverAndDefaultFactoryError(Exception):
    def __init__(self, field_name: str, type_name: str) -> None:
        ...
    


class MissingQueryError(Exception):
    def __init__(self) -> None:
        ...
    


class InvalidDefaultFactoryError(Exception):
    def __init__(self) -> None:
        ...
    


class InvalidCustomContext(Exception):
    """Raised when a custom context object is of the wrong python type."""
    def __init__(self) -> None:
        ...
    


class StrawberryGraphQLError(GraphQLError):
    """Use it when you want to override the graphql.GraphQLError in custom extensions."""
    ...


class ConnectionRejectionError(Exception):
    """Use it when you want to reject a WebSocket connection."""
    def __init__(self, payload: dict[str, object] | None = ...) -> None:
        ...
    


__all__ = ["ConflictingArgumentsError", "DuplicatedTypeName", "FieldWithResolverAndDefaultFactoryError", "FieldWithResolverAndDefaultValueError", "InvalidArgumentTypeError", "InvalidCustomContext", "InvalidDefaultFactoryError", "InvalidSuperclassInterfaceError", "InvalidTypeForUnionMergeError", "InvalidUnionTypeError", "MissingArgumentsAnnotationsError", "MissingFieldAnnotationError", "MissingOptionalDependenciesError", "MissingQueryError", "MissingReturnAnnotationError", "MissingTypesForGenericError", "MultipleStrawberryArgumentsError", "ObjectIsNotAnEnumError", "ObjectIsNotClassError", "PrivateStrawberryFieldError", "ScalarAlreadyRegisteredError", "StrawberryException", "StrawberryGraphQLError", "UnableToFindExceptionSource", "UnallowedReturnTypeForUnion", "UnresolvedFieldTypeError", "UnsupportedTypeError", "WrongNumberOfResultsReturned", "WrongReturnTypeForUnion"]
