"""
This type stub file was generated by pyright.
"""

from functools import cached_property
from typing import TYPE_CHECKING
from .exception import StrawberryException
from rich.console import RenderableType
from .exception_source import ExceptionSource

if TYPE_CHECKING:
    ...
class DuplicatedTypeName(StrawberryException):
    """Raised when the same type with different definition is reused inside a schema."""
    def __init__(self, first_cls: type | None, second_cls: type | None, duplicated_type_name: str) -> None:
        ...
    
    @property
    def __rich_body__(self) -> RenderableType:
        ...
    
    @cached_property
    def exception_source(self) -> ExceptionSource | None:
        ...
    


