"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from functools import cached_property
from typing import TYPE_CHECKING
from rich.console import RenderableType
from .exception_source import ExceptionSource

if TYPE_CHECKING:
    ...
class UnableToFindExceptionSource(Exception):
    """Internal exception raised when we can't find the exception source."""
    ...


class StrawberryException(Exception, ABC):
    message: str
    rich_message: str
    suggestion: str
    annotation_message: str
    def __init__(self, message: str) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    @property
    def documentation_path(self) -> str:
        ...
    
    @property
    def documentation_url(self) -> str:
        ...
    
    @cached_property
    @abstractmethod
    def exception_source(self) -> ExceptionSource | None:
        ...
    
    @property
    def __rich_header__(self) -> RenderableType:
        ...
    
    @property
    def __rich_body__(self) -> RenderableType:
        ...
    
    @property
    def __rich_footer__(self) -> RenderableType:
        ...
    
    def __rich__(self) -> RenderableType | None:
        ...
    


