"""
This type stub file was generated by pyright.
"""

import threading
from collections.abc import Callable
from types import TracebackType

original_threading_exception_hook = ...
ExceptionHandler = Callable[[type[BaseException], BaseException, TracebackType | None], None]
def should_use_rich_exceptions() -> bool:
    ...

def strawberry_exception_handler(exception_type: type[BaseException], exception: BaseException, traceback: TracebackType | None) -> None:
    ...

def strawberry_threading_exception_handler(args: tuple[type[BaseException], BaseException | None, TracebackType | None, threading.Thread | None,]) -> None:
    ...

def reset_exception_handler() -> None:
    ...

def setup_exception_handler() -> None:
    ...

