"""
This type stub file was generated by pyright.
"""

from functools import cached_property
from typing import TYPE_CHECKING
from .exception import StrawberryException
from collections.abc import Iterable
from strawberry.types.base import StrawberryObjectDefinition
from .exception_source import ExceptionSource

if TYPE_CHECKING:
    ...
class InvalidSuperclassInterfaceError(StrawberryException):
    def __init__(self, cls: type[type], input_name: str, interfaces: Iterable[StrawberryObjectDefinition]) -> None:
        ...
    
    @cached_property
    def exception_source(self) -> ExceptionSource | None:
        ...
    


