"""
This type stub file was generated by pyright.
"""

from functools import cached_property
from typing import TYPE_CHECKING
from .exception import StrawberryException
from strawberry.types.arguments import StrawberryArgument
from strawberry.types.fields.resolver import StrawberryResolver
from .exception_source import ExceptionSource

if TYPE_CHECKING:
    ...
class InvalidArgumentTypeError(StrawberryException):
    def __init__(self, resolver: StrawberryResolver, argument: StrawberryArgument) -> None:
        ...
    
    @cached_property
    def exception_source(self) -> ExceptionSource | None:
        ...
    


