"""
This type stub file was generated by pyright.
"""

from functools import cached_property
from typing import TYPE_CHECKING
from .exception import StrawberryException
from strawberry.types.union import StrawberryUnion
from .exception_source import ExceptionSource

if TYPE_CHECKING:
    ...
class InvalidUnionTypeError(StrawberryException):
    """The union is constructed with an invalid type."""
    invalid_type: object
    def __init__(self, union_name: str, invalid_type: object, union_definition: StrawberryUnion | None = ...) -> None:
        ...
    
    @cached_property
    def exception_source(self) -> ExceptionSource | None:
        ...
    


class InvalidTypeForUnionMergeError(StrawberryException):
    """A specialized version of InvalidUnionTypeError for when trying to merge unions using the pipe operator."""
    invalid_type: type
    def __init__(self, union: StrawberryUnion, other: object) -> None:
        ...
    
    @cached_property
    def exception_source(self) -> ExceptionSource | None:
        ...
    


