"""
This type stub file was generated by pyright.
"""

from functools import cached_property
from typing import TYPE_CHECKING
from .exception import StrawberryException
from strawberry.types.fields.resolver import StrawberryResolver
from .exception_source import ExceptionSource

if TYPE_CHECKING:
    ...
class MissingReturnAnnotationError(StrawberryException):
    """The field is missing the return annotation."""
    def __init__(self, field_name: str, resolver: StrawberryResolver) -> None:
        ...
    
    @cached_property
    def exception_source(self) -> ExceptionSource | None:
        ...
    


