"""
This type stub file was generated by pyright.
"""

class MissingOptionalDependenciesError(Exception):
    """Some optional dependencies that are required for a particular task are missing."""
    def __init__(self, *, packages: list[str] | None = ..., extras: list[str] | None = ...) -> None:
        """Initialize the error.

        Args:
            packages: List of packages that are required but missing.
            extras: List of extras that are required but missing.
        """
        ...
    


