"""
This type stub file was generated by pyright.
"""

from functools import cached_property
from typing import TYPE_CHECKING
from .exception import StrawberryException
from strawberry.types.fields.resolver import StrawberryResolver
from .exception_source import ExceptionSource

if TYPE_CHECKING:
    ...
class MissingArgumentsAnnotationsError(StrawberryException):
    """The field is missing the annotation for one or more arguments."""
    def __init__(self, resolver: StrawberryResolver, arguments: list[str]) -> None:
        ...
    
    @property
    def missing_arguments_str(self) -> str:
        ...
    
    @cached_property
    def exception_source(self) -> ExceptionSource | None:
        ...
    


