"""
This type stub file was generated by pyright.
"""

from enum import Enum
from functools import cached_property
from typing import TYPE_CHECKING
from .exception import StrawberryException
from .exception_source import ExceptionSource

if TYPE_CHECKING:
    ...
class ObjectIsNotClassError(StrawberryException):
    class MethodType(Enum):
        INPUT = ...
        INTERFACE = ...
        TYPE = ...
    
    
    def __init__(self, obj: object, method_type: MethodType) -> None:
        ...
    
    @classmethod
    def input(cls, obj: object) -> ObjectIsNotClassError:
        ...
    
    @classmethod
    def interface(cls, obj: object) -> ObjectIsNotClassError:
        ...
    
    @classmethod
    def type(cls, obj: object) -> ObjectIsNotClassError:
        ...
    
    @cached_property
    def exception_source(self) -> ExceptionSource | None:
        ...
    


