"""
This type stub file was generated by pyright.
"""

from functools import cached_property
from typing import TYPE_CHECKING
from .exception import StrawberryException
from enum import Enum
from .exception_source import ExceptionSource

if TYPE_CHECKING:
    ...
class ObjectIsNotAnEnumError(StrawberryException):
    def __init__(self, cls: type[Enum]) -> None:
        ...
    
    @cached_property
    def exception_source(self) -> ExceptionSource | None:
        ...
    


