"""
This type stub file was generated by pyright.
"""

from functools import cached_property
from typing import TYPE_CHECKING
from .exception import StrawberryException
from strawberry.field import StrawberryField
from .exception_source import ExceptionSource

if TYPE_CHECKING:
    ...
class PermissionFailSilentlyRequiresOptionalError(StrawberryException):
    def __init__(self, field: StrawberryField) -> None:
        ...
    
    @cached_property
    def exception_source(self) -> ExceptionSource | None:
        ...
    


