"""
This type stub file was generated by pyright.
"""

from functools import cached_property
from typing import TYPE_CHECKING
from .exception import StrawberryException
from .exception_source import ExceptionSource

if TYPE_CHECKING:
    ...
class PrivateStrawberryFieldError(StrawberryException):
    def __init__(self, field_name: str, cls: type) -> None:
        ...
    
    @cached_property
    def exception_source(self) -> ExceptionSource | None:
        ...
    


