"""
This type stub file was generated by pyright.
"""

from functools import cached_property
from typing import TYPE_CHECKING
from .exception import StrawberryException
from strawberry.types.scalar import ScalarDefinition
from .exception_source import ExceptionSource

if TYPE_CHECKING:
    ...
class ScalarAlreadyRegisteredError(StrawberryException):
    def __init__(self, scalar_definition: ScalarDefinition, other_scalar_definition: ScalarDefinition) -> None:
        ...
    
    @cached_property
    def exception_source(self) -> ExceptionSource | None:
        ...
    


