"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from rich.syntax import Syntax as RichSyntax
from rich.console import Console, ConsoleOptions, RenderResult

if TYPE_CHECKING:
    ...
class Syntax(RichSyntax):
    def __init__(self, code: str, line_range: tuple[int, int], highlight_lines: set[int] | None = ..., line_offset: int = ..., line_annotations: dict[int, str] | None = ...) -> None:
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    


