"""
This type stub file was generated by pyright.
"""

from functools import cached_property
from typing import TYPE_CHECKING
from .exception import StrawberryException
from strawberry.types.field import StrawberryField
from strawberry.types.object_type import StrawberryObjectDefinition
from .exception_source import ExceptionSource

if TYPE_CHECKING:
    ...
class UnresolvedFieldTypeError(StrawberryException):
    def __init__(self, type_definition: StrawberryObjectDefinition, field: StrawberryField) -> None:
        ...
    
    @cached_property
    def exception_source(self) -> ExceptionSource | None:
        ...
    


