"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from strawberry.annotation import StrawberryAnnotation
from strawberry.types.base import StrawberryType
from collections.abc import Iterable, Mapping
from strawberry.schema.config import StrawberryConfig
from strawberry.types.scalar import ScalarDefinition, ScalarWrapper

if TYPE_CHECKING:
    ...
DEPRECATED_NAMES: dict[str, str] = ...
class StrawberryArgumentAnnotation:
    description: str | None
    name: str | None
    deprecation_reason: str | None
    directives: Iterable[object]
    metadata: Mapping[Any, Any]
    graphql_type: Any | None
    def __init__(self, description: str | None = ..., name: str | None = ..., deprecation_reason: str | None = ..., directives: Iterable[object] = ..., metadata: Mapping[Any, Any] | None = ..., graphql_type: Any | None = ...) -> None:
        ...
    


class StrawberryArgument:
    def __init__(self, python_name: str, graphql_name: str | None, type_annotation: StrawberryAnnotation, is_subscription: bool = ..., description: str | None = ..., default: object = ..., deprecation_reason: str | None = ..., directives: Iterable[object] = ..., metadata: Mapping[Any, Any] | None = ...) -> None:
        ...
    
    @property
    def type(self) -> StrawberryType | type:
        ...
    
    @property
    def is_graphql_generic(self) -> bool:
        ...
    
    @property
    def is_maybe(self) -> bool:
        ...
    


def convert_argument(value: object, type_: StrawberryType | type, scalar_registry: Mapping[object, ScalarWrapper | ScalarDefinition], config: StrawberryConfig) -> object:
    ...

def convert_arguments(value: dict[str, Any], arguments: list[StrawberryArgument], scalar_registry: Mapping[object, ScalarWrapper | ScalarDefinition], config: StrawberryConfig) -> dict[str, Any]:
    """Converts a nested dictionary to a dictionary of actual types.

    It deals with conversion of input types to proper dataclasses and
    also uses a sentinel value for unset values.
    """
    ...

def argument(description: str | None = ..., name: str | None = ..., deprecation_reason: str | None = ..., directives: Iterable[object] = ..., metadata: Mapping[Any, Any] | None = ..., graphql_type: Any | None = ...) -> StrawberryArgumentAnnotation:
    """Function to add metadata to an argument, like a description or deprecation reason.

    Args:
        description: The GraphQL description of the argument
        name: The GraphQL name of the argument
        deprecation_reason: The reason why this argument is deprecated,
            setting this will mark the argument as deprecated
        directives: The directives to attach to the argument
        metadata: Metadata to attach to the argument, this can be used
            to store custom data that can be used by custom logic or plugins
        graphql_type: The GraphQL type for the argument, useful when you want to use a
            different type than the one in the schema.

    Returns:
        A StrawberryArgumentAnnotation object that can be used to customise an argument

    Example:
    ```python
    import strawberry


    @strawberry.type
    class Query:
        @strawberry.field
        def example(
            self, info, value: int = strawberry.argument(description="The value")
        ) -> int:
            return value
    ```
    """
    ...

def __getattr__(name: str) -> Any:
    ...

__all__ = ["UNSET", "StrawberryArgument", "StrawberryArgumentAnnotation", "argument", "is_unset"]
