"""
This type stub file was generated by pyright.
"""

from typing import Annotated, Any
from strawberry.annotation import StrawberryAnnotation
from strawberry.types.base import StrawberryType

class StrawberryAutoMeta(type):
    """Metaclass for StrawberryAuto.

    This is used to make sure StrawberryAuto is a singleton and also to
    override the behavior of `isinstance` so that it consider the following
    cases:

        >> isinstance(StrawberryAuto(), StrawberryAuto)
        True
        >> isinstance(StrawberryAnnotation(StrawberryAuto()), StrawberryAuto)
        True
        >> isinstance(Annotated[StrawberryAuto(), object()), StrawberryAuto)
        True

    """
    def __init__(cls, *args: str, **kwargs: Any) -> None:
        ...
    
    def __call__(cls, *args: str, **kwargs: Any) -> Any:
        ...
    
    def __instancecheck__(cls, instance: StrawberryAuto | StrawberryAnnotation | StrawberryType | type) -> bool:
        ...
    


class StrawberryAuto(metaclass=StrawberryAutoMeta):
    def __str__(self) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    


auto = Annotated[Any, StrawberryAuto()]
__all__ = ["auto"]
