"""
This type stub file was generated by pyright.
"""

import dataclasses
from abc import ABC, abstractmethod
from typing import Any, ClassVar, Generic, Literal, TYPE_CHECKING, TypeGuard, TypeVar, overload
from typing_extensions import Protocol, Self, deprecated
from collections.abc import Callable, Mapping, Sequence
from graphql import GraphQLAbstractType, GraphQLResolveInfo
from strawberry.types.field import StrawberryField

if TYPE_CHECKING:
    ...
class StrawberryType(ABC):
    """The base class for all types that Strawberry uses.

    Every type that is decorated by strawberry should have a dunder
    `__strawberry_definition__` with an instance of a StrawberryType that contains
    the parsed information that strawberry created.

    NOTE: ATM this is only true for @type @interface @input follow
    https://github.com/strawberry-graphql/strawberry/issues/2841 to see progress.
    """
    @property
    def type_params(self) -> list[TypeVar]:
        ...
    
    @property
    def is_one_of(self) -> bool:
        ...
    
    @abstractmethod
    def copy_with(self, type_var_map: Mapping[str, StrawberryType | type[WithStrawberryObjectDefinition]]) -> StrawberryType | type[WithStrawberryObjectDefinition]:
        ...
    
    @property
    @abstractmethod
    def is_graphql_generic(self) -> bool:
        ...
    
    def has_generic(self, type_var: TypeVar) -> bool:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    


class StrawberryContainer(StrawberryType):
    def __init__(self, of_type: StrawberryType | type[WithStrawberryObjectDefinition] | type) -> None:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    
    @property
    def type_params(self) -> list[TypeVar]:
        ...
    
    def copy_with(self, type_var_map: Mapping[str, StrawberryType | type[WithStrawberryObjectDefinition]]) -> Self:
        ...
    
    @property
    def is_graphql_generic(self) -> bool:
        ...
    
    def has_generic(self, type_var: TypeVar) -> bool:
        ...
    


class StrawberryList(StrawberryContainer):
    ...


class StrawberryOptional(StrawberryContainer):
    def __init__(self, of_type: StrawberryType | type[WithStrawberryObjectDefinition] | type) -> None:
        ...
    


class StrawberryMaybe(StrawberryOptional):
    ...


class StrawberryTypeVar(StrawberryType):
    def __init__(self, type_var: TypeVar) -> None:
        ...
    
    def copy_with(self, type_var_map: Mapping[str, StrawberryType | type]) -> StrawberryType | type:
        ...
    
    @property
    def is_graphql_generic(self) -> bool:
        ...
    
    def has_generic(self, type_var: TypeVar) -> bool:
        ...
    
    @property
    def type_params(self) -> list[TypeVar]:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    


StrawberryDefinitionType = TypeVar("StrawberryDefinitionType")
class WithStrawberryDefinition(Protocol, Generic[StrawberryDefinitionType]):
    __strawberry_definition__: ClassVar[StrawberryDefinitionType]
    ...


WithStrawberryObjectDefinition = WithStrawberryDefinition["StrawberryObjectDefinition"]
def has_strawberry_definition(obj: Any) -> TypeGuard[type[WithStrawberryDefinition]]:
    ...

def has_object_definition(obj: Any) -> TypeGuard[type[WithStrawberryObjectDefinition]]:
    ...

@overload
def get_object_definition(obj: Any, *, strict: Literal[True]) -> StrawberryObjectDefinition:
    ...

@overload
def get_object_definition(obj: Any, *, strict: bool = ...) -> StrawberryObjectDefinition | None:
    ...

def get_object_definition(obj: Any, *, strict: bool = ...) -> StrawberryObjectDefinition | None:
    ...

@dataclasses.dataclass(eq=False)
class StrawberryObjectDefinition(StrawberryType):
    """Encapsulates definitions for Input / Object / interface GraphQL Types.

    In order get the definition from a decorated object you can use
    `has_object_definition` or `get_object_definition` as a shortcut.
    """
    name: str
    is_input: bool
    is_interface: bool
    origin: type[Any]
    description: str | None
    interfaces: list[StrawberryObjectDefinition]
    extend: bool
    directives: Sequence[object] | None
    is_type_of: Callable[[Any, GraphQLResolveInfo], bool] | None
    resolve_type: Callable[[Any, GraphQLResolveInfo, GraphQLAbstractType], str] | None
    fields: list[StrawberryField]
    concrete_of: StrawberryObjectDefinition | None = ...
    type_var_map: Mapping[str, StrawberryType | type] = ...
    def __post_init__(self) -> None:
        ...
    
    def resolve_generic(self, wrapped_cls: type) -> type:
        ...
    
    def copy_with(self, type_var_map: Mapping[str, StrawberryType | type]) -> type[WithStrawberryObjectDefinition]:
        ...
    
    def get_field(self, python_name: str) -> StrawberryField | None:
        ...
    
    @property
    def is_graphql_generic(self) -> bool:
        ...
    
    @property
    def is_specialized_generic(self) -> bool:
        ...
    
    @property
    def specialized_type_var_map(self) -> dict[str, type] | None:
        ...
    
    @property
    def is_object_type(self) -> bool:
        ...
    
    @property
    def type_params(self) -> list[TypeVar]:
        ...
    
    def is_implemented_by(self, root: type[WithStrawberryObjectDefinition]) -> bool:
        ...
    
    @property
    def is_one_of(self) -> bool:
        ...
    


if TYPE_CHECKING:
    @deprecated("Use StrawberryObjectDefinition instead")
    class TypeDefinition(StrawberryObjectDefinition):
        ...
    
    
else:
    ...
__all__ = ["StrawberryContainer", "StrawberryList", "StrawberryObjectDefinition", "StrawberryOptional", "StrawberryType", "StrawberryTypeVar", "TypeDefinition", "WithStrawberryObjectDefinition", "get_object_definition", "has_object_definition"]
