"""
This type stub file was generated by pyright.
"""

import dataclasses
from collections.abc import Callable, Iterable, Mapping
from enum import EnumMeta
from typing import Any, Literal, TYPE_CHECKING, TypeGuard, TypeVar, overload
from strawberry.types.base import StrawberryType, WithStrawberryDefinition
from typing_extensions import deprecated

@dataclasses.dataclass
class EnumValue:
    name: str
    value: Any
    deprecation_reason: str | None = ...
    directives: Iterable[object] = ...
    description: str | None = ...


@dataclasses.dataclass
class StrawberryEnumDefinition(StrawberryType):
    wrapped_cls: EnumMeta
    name: str
    values: list[EnumValue]
    description: str | None
    directives: Iterable[object] = ...
    def __hash__(self) -> int:
        ...
    
    def copy_with(self, type_var_map: Mapping[str, StrawberryType | type]) -> StrawberryType | type:
        ...
    
    @property
    def is_graphql_generic(self) -> bool:
        ...
    
    @property
    def origin(self) -> type:
        ...
    


@dataclasses.dataclass
class EnumValueDefinition:
    value: Any
    graphql_name: str | None = ...
    deprecation_reason: str | None = ...
    directives: Iterable[object] = ...
    description: str | None = ...
    def __int__(self) -> int:
        ...
    


def enum_value(value: Any, name: str | None = ..., deprecation_reason: str | None = ..., directives: Iterable[object] = ..., description: str | None = ...) -> EnumValueDefinition:
    """Function to customise an enum value, for example to add a description or deprecation reason.

    Args:
        value: The value of the enum member.
        name: The GraphQL name of the enum member.
        deprecation_reason: The deprecation reason of the enum member,
            setting this will mark the enum member as deprecated.
        directives: The directives to attach to the enum member.
        description: The GraphQL description of the enum member.

    Returns:
        An EnumValueDefinition object that can be used to customise an enum member.

    Example:
    ```python
    from enum import Enum
    import strawberry


    @strawberry.enum
    class MyEnum(Enum):
        FIRST_VALUE = strawberry.enum_value(description="The first value")
        SECOND_VALUE = strawberry.enum_value(description="The second value")
    ```
    """
    ...

EnumType = TypeVar("EnumType", bound=EnumMeta)
GraphqlEnumNameFrom = Literal["key", "value"]
@overload
def enum(cls: EnumType, *, name: str | None = ..., description: str | None = ..., directives: Iterable[object] = ..., graphql_name_from: GraphqlEnumNameFrom = ...) -> EnumType:
    ...

@overload
def enum(cls: None = ..., *, name: str | None = ..., description: str | None = ..., directives: Iterable[object] = ..., graphql_name_from: GraphqlEnumNameFrom = ...) -> Callable[[EnumType], EnumType]:
    ...

def enum(cls: EnumType | None = ..., *, name: str | None = ..., description: str | None = ..., directives: Iterable[object] = ..., graphql_name_from: GraphqlEnumNameFrom = ...) -> EnumType | Callable[[EnumType], EnumType]:
    """Annotates an Enum class a GraphQL enum.

    GraphQL enums only have names, while Python enums have names and values,
    Strawberry will by default use the names of the Python enum as the names of the
    GraphQL enum values. You can use the values instead by using mode="value".

    Args:
        cls: The Enum class to be annotated.
        name: The name of the GraphQL enum.
        description: The description of the GraphQL enum.
        directives: The directives to attach to the GraphQL enum.
        graphql_name_from: Whether to use the names (key) or values of the Python enums in GraphQL.

    Returns:
        The decorated Enum class.

    Example:
    ```python
    from enum import Enum
    import strawberry


    @strawberry.enum
    class MyEnum(Enum):
        FIRST_VALUE = "first_value"
        SECOND_VALUE = "second_value"
    ```

    The above code will generate the following GraphQL schema:

    ```graphql
    enum MyEnum {
        FIRST_VALUE
        SECOND_VALUE
    }
    ```

    If name is passed, the name of the GraphQL type will be
    the value passed of name instead of the Enum class name.
    """
    ...

if TYPE_CHECKING:
    @deprecated("Use StrawberryEnumDefinition instead")
    class EnumDefinition(StrawberryEnumDefinition):
        ...
    
    
else:
    ...
WithStrawberryEnumDefinition = WithStrawberryDefinition["StrawberryEnumDefinition"]
def has_enum_definition(obj: Any) -> TypeGuard[type[WithStrawberryEnumDefinition]]:
    ...

__all__ = ["EnumDefinition", "EnumValue", "EnumValueDefinition", "StrawberryEnumDefinition", "enum", "enum_value"]
