"""
This type stub file was generated by pyright.
"""

import dataclasses
from typing import Any, TYPE_CHECKING, runtime_checkable
from typing_extensions import NotRequired, Protocol, TypedDict, deprecated
from graphql import ASTValidationRule
from collections.abc import Iterable
from graphql.error.graphql_error import GraphQLError
from graphql.language import DocumentNode
from strawberry.schema import Schema
from strawberry.schema._graphql_core import GraphQLExecutionResult
from .graphql import OperationType

if TYPE_CHECKING:
    ...
@dataclasses.dataclass
class ExecutionContext:
    query: str | None
    schema: Schema
    allowed_operations: Iterable[OperationType]
    context: Any = ...
    variables: dict[str, Any] | None = ...
    parse_options: ParseOptions = ...
    root_value: Any | None = ...
    validation_rules: tuple[type[ASTValidationRule], ...] = ...
    provided_operation_name: dataclasses.InitVar[str | None] = ...
    graphql_document: DocumentNode | None = ...
    pre_execution_errors: list[GraphQLError] | None = ...
    result: GraphQLExecutionResult | None = ...
    extensions_results: dict[str, Any] = ...
    operation_extensions: dict[str, Any] | None = ...
    def __post_init__(self, provided_operation_name: str | None) -> None:
        ...
    
    @property
    def operation_name(self) -> str | None:
        ...
    
    @property
    def operation_type(self) -> OperationType:
        ...
    
    @property
    @deprecated("Use 'pre_execution_errors' instead")
    def errors(self) -> list[GraphQLError] | None:
        """Deprecated: Use pre_execution_errors instead."""
        ...
    


@dataclasses.dataclass
class ExecutionResult:
    data: dict[str, Any] | None
    errors: list[GraphQLError] | None
    extensions: dict[str, Any] | None = ...


@dataclasses.dataclass
class PreExecutionError(ExecutionResult):
    """Differentiate between a normal execution result and an immediate error.

    Immediate errors are errors that occur before the execution phase i.e validation errors,
    or any other error that occur before we interact with resolvers.

    These errors are required by `graphql-ws-transport` protocol in order to close the operation
    right away once the error is encountered.
    """
    ...


class ParseOptions(TypedDict):
    max_tokens: NotRequired[int]
    ...


@runtime_checkable
class SubscriptionExecutionResult(Protocol):
    def __aiter__(self) -> SubscriptionExecutionResult:
        ...
    
    async def __anext__(self) -> Any:
        ...
    


__all__ = ["ExecutionContext", "ExecutionResult", "ParseOptions", "SubscriptionExecutionResult"]
