"""
This type stub file was generated by pyright.
"""

import dataclasses
import builtins
from collections.abc import Awaitable, Callable, Coroutine, Mapping, Sequence
from functools import cached_property
from typing import Any, Literal, NoReturn, TYPE_CHECKING, TypeAlias, TypeVar, Union, overload
from strawberry.annotation import StrawberryAnnotation
from strawberry.types.base import StrawberryObjectDefinition, StrawberryType, WithStrawberryObjectDefinition
from .fields.resolver import StrawberryResolver
from typing_extensions import Self
from strawberry.extensions.field_extension import FieldExtension
from strawberry.permission import BasePermission
from strawberry.types.arguments import StrawberryArgument
from strawberry.types.info import Info

if TYPE_CHECKING:
    ...
T = TypeVar("T")
_RESOLVER_TYPE_SYNC: TypeAlias = Union[StrawberryResolver[T], Callable[..., T], "staticmethod[Any, T]", "classmethod[Any, Any, T]",]
_RESOLVER_TYPE_ASYNC: TypeAlias = (Callable[..., Coroutine[Any, Any, T]] | Callable[..., Awaitable[T]])
_RESOLVER_TYPE: TypeAlias = _RESOLVER_TYPE_SYNC[T] | _RESOLVER_TYPE_ASYNC[T]
class UNRESOLVED:
    def __new__(cls) -> NoReturn:
        ...
    


FieldType: TypeAlias = (StrawberryType | type[WithStrawberryObjectDefinition | UNRESOLVED])
class StrawberryField(dataclasses.Field):
    type_annotation: StrawberryAnnotation | None
    default_resolver: Callable[[Any, str], object] = ...
    def __init__(self, python_name: str | None = ..., graphql_name: str | None = ..., type_annotation: StrawberryAnnotation | None = ..., origin: type | Callable | staticmethod | classmethod | None = ..., is_subscription: bool = ..., description: str | None = ..., base_resolver: StrawberryResolver | None = ..., permission_classes: list[type[BasePermission]] = ..., default: object = ..., default_factory: Callable[[], Any] | object = ..., metadata: Mapping[Any, Any] | None = ..., deprecation_reason: str | None = ..., directives: Sequence[object] = ..., extensions: list[FieldExtension] = ...) -> None:
        ...
    
    def __copy__(self) -> Self:
        ...
    
    def __call__(self, resolver: _RESOLVER_TYPE) -> Self:
        """Add a resolver to the field."""
        ...
    
    def get_result(self, source: Any, info: Info | None, args: list[Any], kwargs: Any) -> Awaitable[Any] | Any:
        """Calls the resolver defined for the StrawberryField.

        If the field doesn't have a resolver defined we default
        to using the default resolver specified in StrawberryConfig.
        """
        ...
    
    @property
    def is_basic_field(self) -> bool:
        """Returns a boolean indicating if the field is a basic field.

        A "basic" field us a field that has no resolver or
        permission classes, i.e. it just returns the relevant attribute from
        the source object. If it is a basic field we can avoid constructing
        an `Info` object and running any permission checks in the resolver
        which improves performance.
        """
        ...
    
    @property
    def arguments(self) -> list[StrawberryArgument]:
        ...
    
    @arguments.setter
    def arguments(self, value: list[StrawberryArgument]) -> None:
        ...
    
    @property
    def is_graphql_generic(self) -> bool:
        ...
    
    python_name: str = ...
    @property
    def base_resolver(self) -> StrawberryResolver | None:
        ...
    
    @base_resolver.setter
    def base_resolver(self, resolver: StrawberryResolver) -> None:
        ...
    
    @property
    def type(self) -> FieldType:
        ...
    
    @type.setter
    def type(self, type_: Any) -> None:
        ...
    
    @property
    def type_params(self) -> list[TypeVar]:
        ...
    
    def resolve_type(self, *, type_definition: StrawberryObjectDefinition | None = ...) -> FieldType:
        ...
    
    def copy_with(self, type_var_map: Mapping[str, StrawberryType | builtins.type]) -> Self:
        ...
    
    @cached_property
    def is_async(self) -> bool:
        ...
    


@overload
def field(*, resolver: _RESOLVER_TYPE_ASYNC[T], name: str | None = ..., is_subscription: bool = ..., description: str | None = ..., init: Literal[False] = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> T:
    ...

@overload
def field(*, resolver: _RESOLVER_TYPE_SYNC[T], name: str | None = ..., is_subscription: bool = ..., description: str | None = ..., init: Literal[False] = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> T:
    ...

@overload
def field(*, name: str | None = ..., is_subscription: bool = ..., description: str | None = ..., init: Literal[True] = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> Any:
    ...

@overload
def field(resolver: _RESOLVER_TYPE_ASYNC[T], *, name: str | None = ..., is_subscription: bool = ..., description: str | None = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> StrawberryField:
    ...

@overload
def field(resolver: _RESOLVER_TYPE_SYNC[T], *, name: str | None = ..., is_subscription: bool = ..., description: str | None = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> StrawberryField:
    ...

def field(resolver: _RESOLVER_TYPE[Any] | None = ..., *, name: str | None = ..., is_subscription: bool = ..., description: str | None = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ..., init: Literal[True, False] | None = ...) -> Any:
    """Annotates a method or property as a GraphQL field.

    Args:
        resolver: The resolver for the field. This can be a function or a `StrawberryResolver`.
        name: The GraphQL name of the field.
        is_subscription: Whether the field is a subscription field.
        description: The GraphQL description of the field.
        permission_classes: The permission classes required to access the field.
        deprecation_reason: The deprecation reason for the field.
        default: The default value for the field.
        default_factory: The default factory for the field.
        metadata: The metadata for the field.
        directives: The directives for the field.
        extensions: The extensions for the field.
        graphql_type: The GraphQL type for the field, useful when you want to use a
            different type in the resolver than the one in the schema.
        init: This parameter is used by PyRight to determine whether this field is
            added in the constructor or not. It is not used to change any behavior
            at the moment.

    Returns:
        The field.

    This is normally used inside a type declaration:

    ```python
    import strawberry


    @strawberry.type
    class X:
        field_abc: str = strawberry.field(description="ABC")

        @strawberry.field(description="ABC")
        def field_with_resolver(self) -> str:
            return "abc"
    ```

    it can be used both as decorator and as a normal function.
    """
    ...

__all__ = ["StrawberryField", "field"]
