"""
This type stub file was generated by pyright.
"""

import enum
from typing import TYPE_CHECKING
from strawberry.http.types import HTTPMethod

if TYPE_CHECKING:
    ...
class OperationType(enum.Enum):
    QUERY = ...
    MUTATION = ...
    SUBSCRIPTION = ...
    @staticmethod
    def from_http(method: HTTPMethod) -> set[OperationType]:
        ...
    


__all__ = ["OperationType"]
