"""
This type stub file was generated by pyright.
"""

import dataclasses
from functools import cached_property
from typing import Any, Generic, TYPE_CHECKING
from typing_extensions import TypeVar
from .nodes import Selection
from graphql import GraphQLResolveInfo, OperationDefinitionNode
from graphql.language import FieldNode
from graphql.pyutils.path import Path
from strawberry.schema import Schema
from strawberry.types.arguments import StrawberryArgument
from strawberry.types.field import FieldType, StrawberryField

if TYPE_CHECKING:
    ...
ContextType = TypeVar("ContextType", default=Any)
RootValueType = TypeVar("RootValueType", default=Any)
@dataclasses.dataclass
class Info(Generic[ContextType, RootValueType]):
    """Class containing information about the current execution.

    This class is passed to resolvers when there's an argument with type `Info`.

    Example:
    ```python
    import strawberry


    @strawberry.type
    class Query:
        @strawberry.field
        def hello(self, info: strawberry.Info) -> str:
            return f"Hello, {info.context['name']}!"
    ```

    It also supports passing the type of the context and root types:

    ```python
    import strawberry


    @strawberry.type
    class Query:
        @strawberry.field
        def hello(self, info: strawberry.Info[str, str]) -> str:
            return f"Hello, {info.context}!"
    ```
    """
    _raw_info: GraphQLResolveInfo
    _field: StrawberryField
    def __class_getitem__(cls, types: type | tuple[type, ...]) -> type[Info]:
        """Workaround for when passing only one type.

        Python doesn't yet support directly passing only one type to a generic class
        that has typevars with defaults. This is a workaround for that.

        See:
        https://discuss.python.org/t/passing-only-one-typevar-of-two-when-using-defaults/49134
        """
        ...
    
    @property
    def field_name(self) -> str:
        """The name of the current field being resolved."""
        ...
    
    @property
    def schema(self) -> Schema:
        """The schema of the current execution."""
        ...
    
    @property
    def field_nodes(self) -> list[FieldNode]:
        ...
    
    @cached_property
    def selected_fields(self) -> list[Selection]:
        """The fields that were selected on the current field's type."""
        ...
    
    @property
    def context(self) -> ContextType:
        """The context passed to the query execution."""
        ...
    
    @property
    def input_extensions(self) -> dict[str, Any]:
        """The input extensions passed to the query execution."""
        ...
    
    @property
    def root_value(self) -> RootValueType:
        """The root value passed to the query execution."""
        ...
    
    @property
    def variable_values(self) -> dict[str, Any]:
        """The variable values passed to the query execution."""
        ...
    
    @property
    def return_type(self) -> FieldType:
        """The return type of the current field being resolved."""
        ...
    
    @property
    def python_name(self) -> str:
        """The name of the current field being resolved in Python format."""
        ...
    
    @property
    def operation(self) -> OperationDefinitionNode:
        """The operation being executed."""
        ...
    
    @property
    def path(self) -> Path:
        """The path of the current field being resolved."""
        ...
    
    def get_argument_definition(self, name: str) -> StrawberryArgument | None:
        """Get the StrawberryArgument definition for the current field by name."""
        ...
    


__all__ = ["Info"]
