"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, ForwardRef, Generic, TypeVar
from typing_extensions import Self

TypeName = TypeVar("TypeName")
Module = TypeVar("Module")
Other = TypeVar("Other")
@dataclass(frozen=True)
class LazyType(Generic[TypeName, Module]):
    """A class that represents a type that will be resolved at runtime.

    This is useful when you have circular dependencies between types.

    This class is not meant to be used directly, instead use the `strawberry.lazy`
    function.
    """
    type_name: str
    module: str
    package: str | None = ...
    def __class_getitem__(cls, params: tuple[str, str]) -> Self:
        ...
    
    def __or__(self, other: Other) -> object:
        ...
    
    def resolve_type(self) -> type[Any]:
        ...
    
    def __call__(self) -> None:
        ...
    


class StrawberryLazyReference:
    """A class that represents a lazy reference to a type in another module.

    This is useful when you have circular dependencies between types.

    This class is not meant to be used directly, instead use the `strawberry.lazy`
    function.
    """
    def __init__(self, module: str) -> None:
        ...
    
    def resolve_forward_ref(self, forward_ref: ForwardRef) -> LazyType:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    


def lazy(module_path: str) -> StrawberryLazyReference:
    """Creates a lazy reference to a type in another module.

    Args:
        module_path: The path to the module containing the type, supports relative paths
            starting with `.`

    Returns:
        A `StrawberryLazyReference` object that can be used to reference a type in another
        module.

    This is useful when you have circular dependencies between types.

    For example, assuming you have a `Post` type that has a field `author` that
    references a `User` type (which also has a field `posts` that references a list of
    `Post`), you can use `strawberry.lazy` to avoid the circular dependency:

    ```python
    from typing import TYPE_CHECKING, Annotated

    import strawberry

    if TYPE_CHECKING:
        from .users import User


    @strawberry.type
    class Post:
        title: str
        author: Annotated["User", strawberry.lazy(".users")]
    ```
    """
    ...

__all__ = ["LazyType", "StrawberryLazyReference", "lazy"]
