"""
This type stub file was generated by pyright.
"""

from typing import Generic, TYPE_CHECKING, TypeAlias, TypeVar

T = TypeVar("T")
class Some(Generic[T]):
    """A special value that can be used to represent an unset value in a field or argument.

    Similar to `undefined` in JavaScript, this value can be used to differentiate between
    a field that was not set and a field that was set to `None` or `null`.
    """
    __slots__ = ...
    def __init__(self, value: T) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __bool__(self) -> bool:
        ...
    


if TYPE_CHECKING:
    Maybe: TypeAlias = Some[T] | None
else:
    ...
_maybe_re = ...
__all__ = ["Maybe", "Some"]
