"""
This type stub file was generated by pyright.
"""

from typing import Any, Literal, TYPE_CHECKING, overload
from strawberry.types.field import StrawberryField, T, _RESOLVER_TYPE, _RESOLVER_TYPE_ASYNC, _RESOLVER_TYPE_SYNC
from collections.abc import Callable, Mapping, Sequence
from strawberry.extensions.field_extension import FieldExtension
from strawberry.permission import BasePermission

if TYPE_CHECKING:
    ...
@overload
def mutation(*, resolver: _RESOLVER_TYPE_ASYNC[T], name: str | None = ..., description: str | None = ..., init: Literal[False] = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> T:
    ...

@overload
def mutation(*, resolver: _RESOLVER_TYPE_SYNC[T], name: str | None = ..., description: str | None = ..., init: Literal[False] = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> T:
    ...

@overload
def mutation(*, name: str | None = ..., description: str | None = ..., init: Literal[True] = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> Any:
    ...

@overload
def mutation(resolver: _RESOLVER_TYPE_ASYNC[T], *, name: str | None = ..., description: str | None = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> StrawberryField:
    ...

@overload
def mutation(resolver: _RESOLVER_TYPE_SYNC[T], *, name: str | None = ..., description: str | None = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> StrawberryField:
    ...

def mutation(resolver: _RESOLVER_TYPE[Any] | None = ..., *, name: str | None = ..., description: str | None = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ..., init: Literal[True, False] | None = ...) -> Any:
    """Annotates a method or property as a GraphQL mutation.

    Args:
        resolver: The resolver for the field. It can be a sync or async function.
        name: The GraphQL name of the field.
        description: The GraphQL description of the field.
        permission_classes: The permission classes required to access the field.
        deprecation_reason: The deprecation reason for the field.
        default: The default value for the field.
        default_factory: The default factory for the field.
        metadata: The metadata for the field.
        directives: The directives for the field.
        extensions: The extensions for the field.
        graphql_type: The GraphQL type for the field, useful when you want to use a
            different type in the resolver than the one in the schema.
        init: This parameter is used by PyRight to determine whether this field is
            added in the constructor or not. It is not used to change any behavior at
            the moment.

    Returns:
        The field object.

    This is normally used inside a type declaration:

    ```python
    import strawberry


    @strawberry.type
    class Mutation:
        @strawberry.mutation
        def create_post(self, title: str, content: str) -> Post: ...
    ```

    It can be used both as decorator and as a normal function.
    """
    ...

@overload
def subscription(*, resolver: _RESOLVER_TYPE_ASYNC[T], name: str | None = ..., description: str | None = ..., init: Literal[False] = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> T:
    ...

@overload
def subscription(*, resolver: _RESOLVER_TYPE_SYNC[T], name: str | None = ..., description: str | None = ..., init: Literal[False] = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> T:
    ...

@overload
def subscription(*, name: str | None = ..., description: str | None = ..., init: Literal[True] = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> Any:
    ...

@overload
def subscription(resolver: _RESOLVER_TYPE_ASYNC[T], *, name: str | None = ..., description: str | None = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> StrawberryField:
    ...

@overload
def subscription(resolver: _RESOLVER_TYPE_SYNC[T], *, name: str | None = ..., description: str | None = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ...) -> StrawberryField:
    ...

def subscription(resolver: _RESOLVER_TYPE[Any] | None = ..., *, name: str | None = ..., description: str | None = ..., permission_classes: list[type[BasePermission]] | None = ..., deprecation_reason: str | None = ..., default: Any = ..., default_factory: Callable[..., object] | object = ..., metadata: Mapping[Any, Any] | None = ..., directives: Sequence[object] | None = ..., extensions: list[FieldExtension] | None = ..., graphql_type: Any | None = ..., init: Literal[True, False] | None = ...) -> Any:
    """Annotates a method or property as a GraphQL subscription.

    Args:
        resolver: The resolver for the field.
        name: The GraphQL name of the field.
        description: The GraphQL description of the field.
        permission_classes: The permission classes required to access the field.
        deprecation_reason: The deprecation reason for the field.
        default: The default value for the field.
        default_factory: The default factory for the field.
        metadata: The metadata for the field.
        directives: The directives for the field.
        extensions: The extensions for the field.
        graphql_type: The GraphQL type for the field, useful when you want to use a
            different type in the resolver than the one in the schema.
        init: This parameter is used by PyRight to determine whether this field is
            added in the constructor or not. It is not used to change any behavior at
            the moment.

    Returns:
        The field for the subscription.

    This is normally used inside a type declaration:

    ```python
    import strawberry


    @strawberry.type
    class Subscription:
        @strawberry.subscription
        def post_created(self, title: str, content: str) -> Post: ...
    ```

    it can be used both as decorator and as a normal function.
    """
    ...

__all__ = ["mutation", "subscription"]
