"""
This type stub file was generated by pyright.
"""

import dataclasses
from typing import Any, TYPE_CHECKING, Union
from graphql.language import ArgumentNode as GQLArgumentNode, DirectiveNode as GQLDirectiveNode, FieldNode as GQLFieldNode, FragmentSpreadNode as GQLFragmentSpreadNode, InlineFragmentNode as GQLInlineFragmentNode, ValueNode as GQLValueNode
from collections.abc import Collection, Iterable
from graphql import GraphQLResolveInfo

"""Abstraction layer for graphql-core field nodes.

Call `convert_sections` on a list of GraphQL `FieldNode`s,
such as in `info.field_nodes`.

If a node has only one useful value, it's value is inlined.

If a list of nodes have unique names, it's transformed into a mapping.
Note Python dicts maintain ordering (for all supported versions).
"""
if TYPE_CHECKING:
    ...
Arguments = dict[str, Any]
Directives = dict[str, Arguments]
Selection = Union["SelectedField", "FragmentSpread", "InlineFragment"]
def convert_value(info: GraphQLResolveInfo, node: GQLValueNode) -> Any:
    """Return useful value from any node."""
    ...

def convert_arguments(info: GraphQLResolveInfo, nodes: Iterable[GQLArgumentNode]) -> Arguments:
    """Return mapping of arguments."""
    ...

def convert_directives(info: GraphQLResolveInfo, nodes: Iterable[GQLDirectiveNode]) -> Directives:
    """Return mapping of directives."""
    ...

def convert_selections(info: GraphQLResolveInfo, field_nodes: Collection[GQLFieldNode]) -> list[Selection]:
    """Return typed `Selection` based on node type."""
    ...

@dataclasses.dataclass
class FragmentSpread:
    """Wrapper for a FragmentSpreadNode."""
    name: str
    type_condition: str
    directives: Directives
    selections: list[Selection]
    @classmethod
    def from_node(cls, info: GraphQLResolveInfo, node: GQLFragmentSpreadNode) -> FragmentSpread:
        ...
    


@dataclasses.dataclass
class InlineFragment:
    """Wrapper for a InlineFragmentNode."""
    type_condition: str
    selections: list[Selection]
    directives: Directives
    @classmethod
    def from_node(cls, info: GraphQLResolveInfo, node: GQLInlineFragmentNode) -> InlineFragment:
        ...
    


@dataclasses.dataclass
class SelectedField:
    """Wrapper for a FieldNode."""
    name: str
    directives: Directives
    arguments: Arguments
    selections: list[Selection]
    alias: str | None = ...
    @classmethod
    def from_node(cls, info: GraphQLResolveInfo, node: GQLFieldNode) -> SelectedField:
        ...
    


__all__ = ["FragmentSpread", "InlineFragment", "SelectedField", "convert_selections"]
