"""
This type stub file was generated by pyright.
"""

from typing import Annotated, TypeVar

class StrawberryPrivate:
    ...


T = TypeVar("T")
Private = Annotated[T, StrawberryPrivate()]
def is_private(type_: object) -> bool:
    ...

__all__ = ["Private", "is_private"]
