"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, NewType, TYPE_CHECKING, TypeVar, overload
from strawberry.types.base import StrawberryType
from collections.abc import Callable, Iterable, Mapping
from graphql import GraphQLScalarType

if TYPE_CHECKING:
    ...
_T = TypeVar("_T", bound=type | NewType)
def identity(x: _T) -> _T:
    ...

@dataclass
class ScalarDefinition(StrawberryType):
    name: str
    description: str | None
    specified_by_url: str | None
    serialize: Callable | None
    parse_value: Callable | None
    parse_literal: Callable | None
    directives: Iterable[object] = ...
    origin: GraphQLScalarType | type | None = ...
    implementation: GraphQLScalarType | None = ...
    _source_file: str | None = ...
    _source_line: int | None = ...
    def copy_with(self, type_var_map: Mapping[str, StrawberryType | type]) -> StrawberryType | type:
        ...
    
    @property
    def is_graphql_generic(self) -> bool:
        ...
    


class ScalarWrapper:
    _scalar_definition: ScalarDefinition
    def __init__(self, wrap: Callable[[Any], Any]) -> None:
        ...
    
    def __call__(self, *args: str, **kwargs: Any) -> Any:
        ...
    
    def __or__(self, other: StrawberryType | type) -> StrawberryType:
        ...
    


@overload
def scalar(cls: None = ..., *, name: str, description: str | None = ..., specified_by_url: str | None = ..., serialize: Callable = ..., parse_value: Callable | None = ..., parse_literal: Callable | None = ..., directives: Iterable[object] = ...) -> ScalarDefinition:
    ...

@overload
def scalar(cls: None = ..., *, name: None = ..., description: str | None = ..., specified_by_url: str | None = ..., serialize: Callable = ..., parse_value: Callable | None = ..., parse_literal: Callable | None = ..., directives: Iterable[object] = ...) -> Callable[[_T], _T]:
    ...

@overload
def scalar(cls: _T, *, name: str | None = ..., description: str | None = ..., specified_by_url: str | None = ..., serialize: Callable = ..., parse_value: Callable | None = ..., parse_literal: Callable | None = ..., directives: Iterable[object] = ...) -> _T:
    ...

def scalar(cls: _T | None = ..., *, name: str | None = ..., description: str | None = ..., specified_by_url: str | None = ..., serialize: Callable = ..., parse_value: Callable | None = ..., parse_literal: Callable | None = ..., directives: Iterable[object] = ...) -> Any:
    """Annotates a class or type as a GraphQL custom scalar.

    This function can be used in three ways:

    1. With a `name` but no `cls`: Returns a `ScalarDefinition` for use in
       `StrawberryConfig.scalar_map`. This is the recommended approach as it
       provides proper type checking support.

    2. As a decorator (no `cls`): Returns a decorator function. When the `cls`
       argument is provided inline, this is deprecated in favor of using
       `scalar_map`.

    3. With a `cls` argument (deprecated): Wraps the class/type directly.
       This approach is deprecated because it causes type checker issues.
       Use `scalar_map` in `StrawberryConfig` instead.

    Args:
        cls: The class or type to annotate (deprecated, use scalar_map instead).
        name: The GraphQL name of the scalar.
        description: The description of the scalar.
        specified_by_url: The URL of the specification.
        serialize: The function to serialize the scalar.
        parse_value: The function to parse the value.
        parse_literal: The function to parse the literal.
        directives: The directives to apply to the scalar.

    Returns:
        A `ScalarDefinition` when called with `name` only, a decorator function
        when called without arguments, or the wrapped type when called with `cls`.

    Example usages:

    Recommended approach using scalar_map:

    ```python
    from typing import NewType
    import strawberry
    from strawberry.schema.config import StrawberryConfig

    # Define the type
    Base64 = NewType("Base64", bytes)

    # Configure the scalar in schema config
    schema = strawberry.Schema(
        query=Query,
        config=StrawberryConfig(
            scalar_map={
                Base64: strawberry.scalar(
                    name="Base64",
                    serialize=lambda v: base64.b64encode(v).decode(),
                    parse_value=lambda v: base64.b64decode(v),
                )
            }
        ),
    )
    ```

    Legacy approach (deprecated):

    ```python
    Base64Encoded = strawberry.scalar(
        NewType("Base64Encoded", bytes),
        serialize=base64.b64encode,
        parse_value=base64.b64decode,
    )
    ```
    """
    ...

__all__ = ["ScalarDefinition", "ScalarWrapper", "scalar"]
