"""
This type stub file was generated by pyright.
"""

from typing import Any, NoReturn, TYPE_CHECKING, TypeVar
from graphql import GraphQLTypeResolver
from strawberry.annotation import StrawberryAnnotation
from strawberry.types.base import StrawberryType
from collections.abc import Collection, Iterable, Mapping
from strawberry.schema.types.concrete_type import TypeMap

if TYPE_CHECKING:
    ...
class StrawberryUnion(StrawberryType):
    _source_file: str | None = ...
    _source_line: int | None = ...
    def __init__(self, name: str | None = ..., type_annotations: tuple[StrawberryAnnotation, ...] = ..., description: str | None = ..., directives: Iterable[object] = ...) -> None:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __or__(self, other: StrawberryType | type) -> StrawberryType:
        ...
    
    @property
    def types(self) -> tuple[StrawberryType, ...]:
        ...
    
    @property
    def type_params(self) -> list[TypeVar]:
        ...
    
    @property
    def is_graphql_generic(self) -> bool:
        ...
    
    def copy_with(self, type_var_map: Mapping[str, StrawberryType | type]) -> StrawberryType:
        ...
    
    def __call__(self, *args: str, **kwargs: Any) -> NoReturn:
        """Do not use.

        Used to bypass
        https://github.com/python/cpython/blob/5efb1a77e75648012f8b52960c8637fc296a5c6d/Lib/typing.py#L148-L149
        """
        ...
    
    def get_type_resolver(self, type_map: TypeMap) -> GraphQLTypeResolver:
        ...
    
    @staticmethod
    def is_valid_union_type(type_: object) -> bool:
        ...
    


def union(name: str, types: Collection[type[Any]] | None = ..., *, description: str | None = ..., directives: Iterable[object] = ...) -> StrawberryUnion:
    """Creates a new named Union type.

    Args:
        name: The GraphQL name of the Union type.
        types: The types that the Union can be.
            (Deprecated, use `Annotated[U, strawberry.union("Name")]` instead)
        description: The  GraphQL description of the Union type.
        directives: The directives to attach to the Union type.

    Example usages:

    ```python
    import strawberry
    from typing import Annotated

    @strawberry.type
    class A: ...

    @strawberry.type
    class B: ...

    MyUnion = Annotated[A | B, strawberry.union("Name")]
    """
    ...

__all__ = ["StrawberryUnion", "union"]
