"""
This type stub file was generated by pyright.
"""

from typing import Any
from typing_extensions import Self

DEPRECATED_NAMES: dict[str, str] = ...
class UnsetType:
    __instance: Self | None = ...
    def __new__(cls: type[Self]) -> Self:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __bool__(self) -> bool:
        ...
    


UNSET: Any = ...
def __getattr__(name: str) -> Any:
    ...

__all__ = ["UNSET"]
