"""
This type stub file was generated by pyright.
"""

from typing import Any

"""Optimized is_awaitable implementation for GraphQL execution.

This module provides a highly optimized is_awaitable function that adds a fast path
for common synchronous types, significantly improving performance when dealing with
large result sets containing primitive values.
"""
__all__ = ["optimized_is_awaitable"]
_NON_AWAITABLE_TYPES: frozenset[type] = ...
def optimized_is_awaitable(value: Any) -> bool:
    """Return true if object can be passed to an ``await`` expression.

    This is an optimized version of graphql-core's is_awaitable that adds a fast path
    for common synchronous types. For large result sets containing mostly primitive
    values (ints, strings, lists, etc.), this can provide significant performance
    improvements.

    Performance characteristics:
    - Fast path for primitives: O(1) type lookup
    - Falls back to graphql-core's is_awaitable for other types

    Args:
        value: The value to check

    Returns:
        True if the value is awaitable, False otherwise
    """
    ...

