"""
This type stub file was generated by pyright.
"""

from collections.abc import AsyncGenerator, AsyncIterable, AsyncIterator, Awaitable, Callable
from contextlib import asynccontextmanager
from typing import Any, TypeVar

_T = TypeVar("_T")
_R = TypeVar("_R")
@asynccontextmanager
async def aclosing(thing: _T) -> AsyncGenerator[_T, None]:
    """Ensure that an async generator is closed properly.

    Port from the stdlib contextlib.asynccontextmanager. Can be removed
    and replaced with the stdlib version when we drop support for Python
    versions before 3.10.
    """
    ...

async def aenumerate(iterable: AsyncIterator[_T] | AsyncIterable[_T]) -> AsyncIterator[tuple[int, _T]]:
    """Async version of enumerate."""
    ...

async def aislice(aiterable: AsyncIterator[_T] | AsyncIterable[_T], start: int | None = ..., stop: int | None = ..., step: int | None = ...) -> AsyncIterator[_T]:
    """Async version of itertools.islice."""
    ...

async def asyncgen_to_list(generator: AsyncGenerator[_T, Any]) -> list[_T]:
    """Convert an async generator to a list."""
    ...

async def resolve_awaitable(awaitable: Awaitable[_T], callback: Callable[[_T], _R]) -> _R:
    """Resolves an awaitable object and calls a callback with the resolved value."""
    ...

__all__ = ["aenumerate", "aislice", "asyncgen_to_list", "resolve_awaitable"]
