"""
This type stub file was generated by pyright.
"""

from collections.abc import AsyncIterator, Awaitable, Iterator
from typing import TypeAlias, TypeVar

T = TypeVar("T")
AwaitableOrValue: TypeAlias = Awaitable[T] | T
AsyncIteratorOrIterator: TypeAlias = AsyncIterator[T] | Iterator[T]
async def await_maybe(value: AwaitableOrValue[T]) -> T:
    ...

__all__ = ["AsyncIteratorOrIterator", "AwaitableOrValue", "await_maybe"]
