"""
This type stub file was generated by pyright.
"""

from typing import Any

class DEPRECATION_MESSAGES:
    _TYPE_DEFINITION = ...
    _ENUM_DEFINITION = ...


class DeprecatedDescriptor:
    def __init__(self, msg: str, alias: object, attr_name: str) -> None:
        ...
    
    def warn(self) -> None:
        ...
    
    def __get__(self, obj: object | None, type: type | None = ...) -> Any:
        ...
    
    def inject(self, klass: type) -> None:
        ...
    


__all__ = ["DEPRECATION_MESSAGES", "DeprecatedDescriptor"]
