"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from strawberry.schema.schema import Schema

if TYPE_CHECKING:
    ...
def locate_definition(schema_symbol: Schema, symbol: str) -> str | None:
    ...

