"""
This type stub file was generated by pyright.
"""

import logging
from typing import Any, Final, TYPE_CHECKING
from graphql.error import GraphQLError
from strawberry.types import ExecutionContext

if TYPE_CHECKING:
    ...
class StrawberryLogger:
    logger: Final[logging.Logger] = ...
    @classmethod
    def error(cls, error: GraphQLError, execution_context: ExecutionContext | None = ..., **logger_kwargs: Any) -> None:
        ...
    


__all__ = ["StrawberryLogger"]
