"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from graphql.language import DocumentNode, OperationDefinitionNode
from strawberry.types.graphql import OperationType

if TYPE_CHECKING:
    ...
def get_first_operation(graphql_document: DocumentNode) -> OperationDefinitionNode | None:
    ...

def get_operation_type(graphql_document: DocumentNode, operation_name: str | None = ...) -> OperationType:
    ...

__all__ = ["get_first_operation", "get_operation_type"]
