"""
This type stub file was generated by pyright.
"""

def to_camel_case(snake_str: str) -> str:
    ...

TO_KEBAB_CASE_RE = ...
def to_kebab_case(name: str) -> str:
    ...

def capitalize_first(name: str) -> str:
    ...

def to_snake_case(name: str) -> str:
    ...

__all__ = ["capitalize_first", "to_camel_case", "to_kebab_case", "to_snake_case"]
