"""
This type stub file was generated by pyright.
"""

from functools import lru_cache
from typing import Any, ForwardRef, TypeGuard, _GenericAlias

@lru_cache
def get_generic_alias(type_: type) -> type:
    """Get the generic alias for a type.

    Given a type, its generic alias from `typing` module will be returned
    if it exists. For example:

    ```python
    get_generic_alias(list)
    # typing.List

    get_generic_alias(dict)
    # typing.Dict
    ```

    This is mostly useful for python versions prior to 3.9, to get a version
    of a concrete type which supports `__class_getitem__`. In 3.9+ types like
    `list`/`dict`/etc are subscriptable and can be used directly instead
    of their generic alias version.
    """
    ...

def is_generic_alias(type_: Any) -> TypeGuard[_GenericAlias]:
    """Returns True if the type is a generic alias."""
    ...

def is_list(annotation: object) -> bool:
    """Returns True if annotation is a List."""
    ...

def is_union(annotation: object) -> bool:
    """Returns True if annotation is a Union."""
    ...

def is_optional(annotation: type) -> bool:
    """Returns True if the annotation is Optional[SomeType]."""
    ...

def get_optional_annotation(annotation: type) -> type:
    ...

def get_list_annotation(annotation: type) -> type:
    ...

def is_concrete_generic(annotation: type) -> bool:
    ...

def is_generic_subclass(annotation: type) -> bool:
    ...

def is_generic(annotation: type) -> bool:
    """Returns True if the annotation is or extends a generic."""
    ...

def is_type_var(annotation: type) -> bool:
    """Returns True if the annotation is a TypeVar."""
    ...

def is_classvar(cls: type, annotation: ForwardRef | str) -> bool:
    """Returns True if the annotation is a ClassVar."""
    ...

def type_has_annotation(type_: object, annotation: type) -> bool:
    """Returns True if the type_ has been annotated with annotation."""
    ...

def get_parameters(annotation: type) -> tuple[object] | tuple[()]:
    ...

def eval_type(type_: Any, globalns: dict | None = ..., localns: dict | None = ...) -> type:
    """Evaluates a type, resolving forward references."""
    ...

__all__ = ["eval_type", "get_generic_alias", "get_list_annotation", "get_optional_annotation", "get_parameters", "is_classvar", "is_concrete_generic", "is_generic", "is_generic_alias", "is_generic_subclass", "is_list", "is_optional", "is_type_var", "is_union", "type_has_annotation"]
