"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from typing import Any

def replace_placeholders_with_files(operations_with_placeholders: dict[str, Any], files_map: Mapping[str, Any], files: Mapping[str, Any]) -> dict[str, Any]:
    ...

__all__ = ["replace_placeholders_with_files"]
