"""
This type stub file was generated by pyright.
"""

import libcst as cst
import libcst.matchers as m
from typing import TYPE_CHECKING
from libcst._nodes.expression import BaseExpression, Call
from libcst.codemod import CodemodContext, VisitorBasedCodemodCommand

if TYPE_CHECKING:
    ...
class ConvertUnionToAnnotatedUnion(VisitorBasedCodemodCommand):
    DESCRIPTION: str = ...
    def __init__(self, context: CodemodContext, use_pipe_syntax: bool = ..., use_typing_extensions: bool = ...) -> None:
        ...
    
    def visit_Module(self, node: cst.Module) -> bool | None:
        ...
    
    @m.visit(m.ImportFrom(m.Name("strawberry"), [m.ZeroOrMore(), m.ImportAlias(m.Name("union")), m.ZeroOrMore()]))
    def visit_import_from(self, original_node: cst.ImportFrom) -> None:
        ...
    
    @m.leave(m.Call(func=m.Attribute(value=m.Name("strawberry"), attr=m.Name("union")) | m.Name("union")))
    def leave_union_call(self, original_node: Call, updated_node: Call) -> BaseExpression:
        ...
    


