"""
This type stub file was generated by pyright.
"""

import libcst as cst
import libcst.matchers as m
from libcst._nodes.expression import BaseExpression
from libcst.codemod import CodemodContext, VisitorBasedCodemodCommand

class ConvertMaybeToOptional(VisitorBasedCodemodCommand):
    DESCRIPTION: str = ...
    def __init__(self, context: CodemodContext, use_pipe_syntax: bool = ...) -> None:
        ...
    
    @m.leave(m.Subscript(value=m.Attribute(value=m.Name("strawberry"), attr=m.Name("Maybe")) | m.Name("Maybe")))
    def leave_maybe_subscript(self, original_node: cst.Subscript, updated_node: cst.Subscript) -> BaseExpression:
        ...
    


