"""
This type stub file was generated by pyright.
"""

import libcst as cst
from libcst.codemod import CodemodContext, VisitorBasedCodemodCommand

SCALAR_REPLACEMENTS: dict[str, tuple[str, str, str | None]] = ...
class ReplaceScalarWrappers(VisitorBasedCodemodCommand):
    DESCRIPTION: str = ...
    METADATA_DEPENDENCIES = ...
    def __init__(self, context: CodemodContext) -> None:
        ...
    
    def visit_ImportFrom(self, node: cst.ImportFrom) -> bool | None:
        """Track imports from strawberry.schema.types.base_scalars."""
        ...
    
    def leave_ImportFrom(self, original_node: cst.ImportFrom, updated_node: cst.ImportFrom) -> cst.ImportFrom | cst.RemovalSentinel:
        """Remove or update imports from strawberry.schema.types.base_scalars."""
        ...
    
    def leave_Name(self, original_node: cst.Name, updated_node: cst.Name) -> cst.BaseExpression:
        """Replace usages of imported scalar wrappers with their actual types."""
        ...
    


