"""
This type stub file was generated by pyright.
"""

import libcst as cst
from libcst.codemod import CodemodContext, VisitorBasedCodemodCommand

class UpdateImportsCodemod(VisitorBasedCodemodCommand):
    def __init__(self, context: CodemodContext) -> None:
        ...
    
    def leave_ImportFrom(self, node: cst.ImportFrom, updated_node: cst.ImportFrom) -> cst.ImportFrom:
        ...
    


