"""
This type stub file was generated by pyright.
"""

import strawberry
from typing import Any
from strawberry.extensions.field_extension import AsyncExtensionResolver, FieldExtension, SyncExtensionResolver
from strawberry.types.field import StrawberryField

class InputMutationExtension(FieldExtension):
    def apply(self, field: StrawberryField) -> None:
        ...
    
    def resolve(self, next_: SyncExtensionResolver, source: Any, info: strawberry.Info, **kwargs: Any) -> Any:
        ...
    
    async def resolve_async(self, next_: AsyncExtensionResolver, source: Any, info: strawberry.Info, **kwargs: Any) -> Any:
        ...
    


__all__ = ["InputMutationExtension"]
