"""
This type stub file was generated by pyright.
"""

import warnings
from datetime import timedelta
from json import JSONDecodeError
from typing import TYPE_CHECKING, TypeGuard
from cross_web import HTTPException, StarletteRequestAdapter
from starlette import status
from starlette.requests import Request
from starlette.responses import HTMLResponse, PlainTextResponse, Response, StreamingResponse
from starlette.websockets import WebSocket, WebSocketDisconnect, WebSocketState
from strawberry.http.async_base_view import AsyncBaseHTTPView, AsyncWebSocketAdapter
from strawberry.http.exceptions import NonJsonMessageReceived, NonTextMessageReceived, WebSocketDisconnected
from strawberry.http.typevars import Context, RootValue
from strawberry.subscriptions import GRAPHQL_TRANSPORT_WS_PROTOCOL, GRAPHQL_WS_PROTOCOL
from collections.abc import AsyncGenerator, AsyncIterator, Callable, Mapping, Sequence
from starlette.types import Receive, Scope, Send
from strawberry.http import GraphQLHTTPResponse
from strawberry.http.ides import GraphQL_IDE
from strawberry.schema import BaseSchema

if TYPE_CHECKING:
    ...
class ASGIWebSocketAdapter(AsyncWebSocketAdapter):
    def __init__(self, view: AsyncBaseHTTPView, request: WebSocket, response: WebSocket) -> None:
        ...
    
    async def iter_json(self, *, ignore_parsing_errors: bool = ...) -> AsyncGenerator[object, None]:
        ...
    
    async def send_json(self, message: Mapping[str, object]) -> None:
        ...
    
    async def close(self, code: int, reason: str) -> None:
        ...
    


class GraphQL(AsyncBaseHTTPView[Request, Response, Response, WebSocket, WebSocket, Context, RootValue,]):
    allow_queries_via_get = ...
    request_adapter_class = StarletteRequestAdapter
    websocket_adapter_class = ...
    def __init__(self, schema: BaseSchema, graphiql: bool | None = ..., graphql_ide: GraphQL_IDE | None = ..., allow_queries_via_get: bool = ..., keep_alive: bool = ..., keep_alive_interval: float = ..., subscription_protocols: Sequence[str] = ..., connection_init_wait_timeout: timedelta = ..., multipart_uploads_enabled: bool = ...) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    
    async def get_root_value(self, request: Request | WebSocket) -> RootValue | None:
        ...
    
    async def get_context(self, request: Request | WebSocket, response: Response | WebSocket) -> Context:
        ...
    
    async def get_sub_response(self, request: Request | WebSocket) -> Response:
        ...
    
    async def render_graphql_ide(self, request: Request) -> Response:
        ...
    
    def create_response(self, response_data: GraphQLHTTPResponse | list[GraphQLHTTPResponse], sub_response: Response) -> Response:
        ...
    
    async def create_streaming_response(self, request: Request | WebSocket, stream: Callable[[], AsyncIterator[str]], sub_response: Response, headers: dict[str, str]) -> Response:
        ...
    
    def is_websocket_request(self, request: Request | WebSocket) -> TypeGuard[WebSocket]:
        ...
    
    async def pick_websocket_subprotocol(self, request: WebSocket) -> str | None:
        ...
    
    async def create_websocket_response(self, request: WebSocket, subprotocol: str | None) -> WebSocket:
        ...
    


