"""
This type stub file was generated by pyright.
"""

from typing import Any, Generic, TYPE_CHECKING
from strawberry.http.typevars import Context, RootValue
from strawberry.subscriptions.protocols.graphql_ws.types import ConnectionInitMessage, ConnectionTerminateMessage, OperationMessage, StartMessage, StopMessage
from strawberry.types.execution import ExecutionResult
from strawberry.http.async_base_view import AsyncBaseHTTPView, AsyncWebSocketAdapter
from strawberry.schema import BaseSchema

if TYPE_CHECKING:
    ...
class BaseGraphQLWSHandler(Generic[Context, RootValue]):
    def __init__(self, view: AsyncBaseHTTPView[Any, Any, Any, Any, Any, Context, RootValue], websocket: AsyncWebSocketAdapter, context: Context, root_value: RootValue | None, schema: BaseSchema, keep_alive: bool, keep_alive_interval: float | None) -> None:
        ...
    
    async def handle(self) -> None:
        ...
    
    async def handle_message(self, message: OperationMessage) -> None:
        ...
    
    async def handle_connection_init(self, message: ConnectionInitMessage) -> None:
        ...
    
    async def handle_connection_terminate(self, message: ConnectionTerminateMessage) -> None:
        ...
    
    async def handle_start(self, message: StartMessage) -> None:
        ...
    
    async def handle_stop(self, message: StopMessage) -> None:
        ...
    
    async def handle_keep_alive(self) -> None:
        ...
    
    async def handle_async_results(self, operation_id: str, query: str, operation_name: str | None, variables: dict[str, object] | None) -> None:
        ...
    
    async def cleanup_operation(self, operation_id: str) -> None:
        ...
    
    async def cleanup(self) -> None:
        ...
    
    async def send_data_message(self, execution_result: ExecutionResult, operation_id: str) -> None:
        ...
    
    async def send_message(self, message: OperationMessage) -> None:
        ...
    


__all__ = ["BaseGraphQLWSHandler"]
