"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from strawberry.extensions.base_extension import SchemaExtension
from collections.abc import Iterator
from graphql import ASTValidationRule

if TYPE_CHECKING:
    ...
class AddValidationRules(SchemaExtension):
    """Add graphql-core validation rules.

    Example:
    ```python
    import strawberry
    from strawberry.extensions import AddValidationRules
    from graphql import ValidationRule, GraphQLError


    class MyCustomRule(ValidationRule):
        def enter_field(self, node, *args) -> None:
            if node.name.value == "secret_field":
                self.report_error(GraphQLError("Can't query field 'secret_field'"))


    schema = strawberry.Schema(
        Query,
        extensions=[
            AddValidationRules(
                [
                    MyCustomRule,
                ]
            ),
        ],
    )
    ```
    """
    validation_rules: list[type[ASTValidationRule]]
    def __init__(self, validation_rules: list[type[ASTValidationRule]]) -> None:
        ...
    
    def on_operation(self) -> Iterator[None]:
        ...
    


__all__ = ["AddValidationRules"]
