"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from enum import Enum
from typing import Any, TYPE_CHECKING
from strawberry.utils.await_maybe import AsyncIteratorOrIterator, AwaitableOrValue
from graphql import GraphQLResolveInfo
from strawberry.types import ExecutionContext

if TYPE_CHECKING:
    ...
class LifecycleStep(Enum):
    OPERATION = ...
    VALIDATION = ...
    PARSE = ...
    RESOLVE = ...


class SchemaExtension:
    execution_context: ExecutionContext
    def __init__(self, *, execution_context: ExecutionContext | None = ...) -> None:
        ...
    
    def on_operation(self) -> AsyncIteratorOrIterator[None]:
        """Called before and after a GraphQL operation (query / mutation) starts."""
        ...
    
    def on_validate(self) -> AsyncIteratorOrIterator[None]:
        """Called before and after the validation step."""
        ...
    
    def on_parse(self) -> AsyncIteratorOrIterator[None]:
        """Called before and after the parsing step."""
        ...
    
    def on_execute(self) -> AsyncIteratorOrIterator[None]:
        """Called before and after the execution step."""
        ...
    
    def resolve(self, _next: Callable, root: Any, info: GraphQLResolveInfo, *args: str, **kwargs: Any) -> AwaitableOrValue[object]:
        ...
    
    def get_results(self) -> AwaitableOrValue[dict[str, Any]]:
        ...
    


Hook = Callable[[SchemaExtension], AsyncIteratorOrIterator[None]]
HOOK_METHODS: set[str] = ...
__all__ = ["HOOK_METHODS", "Hook", "LifecycleStep", "SchemaExtension"]
