"""
This type stub file was generated by pyright.
"""

import contextlib
from typing import Any, NamedTuple, TYPE_CHECKING
from strawberry.extensions import SchemaExtension
from strawberry.utils.await_maybe import AwaitableOrValue
from collections.abc import Callable
from types import TracebackType

if TYPE_CHECKING:
    ...
class WrappedHook(NamedTuple):
    extension: SchemaExtension
    hook: Callable[..., contextlib.AbstractAsyncContextManager[None] | contextlib.AbstractContextManager[None],]
    is_async: bool
    ...


class ExtensionContextManagerBase:
    __slots__ = ...
    def __init_subclass__(cls) -> None:
        ...
    
    HOOK_NAME: str
    DEPRECATION_MESSAGE: str
    LEGACY_ENTER: str
    LEGACY_EXIT: str
    def __init__(self, extensions: list[SchemaExtension]) -> None:
        ...
    
    def get_hook(self, extension: SchemaExtension) -> WrappedHook | None:
        ...
    
    @staticmethod
    def from_legacy(extension: SchemaExtension, on_start: Callable[[], None] | None = ..., on_end: Callable[[], None] | None = ...) -> WrappedHook:
        ...
    
    @staticmethod
    def from_callable(extension: SchemaExtension, func: Callable[[SchemaExtension], AwaitableOrValue[Any]]) -> WrappedHook:
        ...
    
    def __enter__(self) -> None:
        ...
    
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> None:
        ...
    
    async def __aenter__(self) -> None:
        ...
    
    async def __aexit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> None:
        ...
    


class OperationContextManager(ExtensionContextManagerBase):
    HOOK_NAME = ...
    LEGACY_ENTER = ...
    LEGACY_EXIT = ...


class ValidationContextManager(ExtensionContextManagerBase):
    HOOK_NAME = ...
    LEGACY_ENTER = ...
    LEGACY_EXIT = ...


class ParsingContextManager(ExtensionContextManagerBase):
    HOOK_NAME = ...
    LEGACY_ENTER = ...
    LEGACY_EXIT = ...


class ExecutingContextManager(ExtensionContextManagerBase):
    HOOK_NAME = ...
    LEGACY_ENTER = ...
    LEGACY_EXIT = ...


