"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from strawberry.extensions import SchemaExtension
from strawberry.utils.await_maybe import AwaitableOrValue
from collections.abc import Callable
from graphql import DirectiveNode, GraphQLResolveInfo
from strawberry.directive import StrawberryDirective

if TYPE_CHECKING:
    ...
SPECIFIED_DIRECTIVES = ...
class DirectivesExtension(SchemaExtension):
    async def resolve(self, _next: Callable, root: Any, info: GraphQLResolveInfo, *args: str, **kwargs: Any) -> AwaitableOrValue[Any]:
        ...
    


class DirectivesExtensionSync(SchemaExtension):
    def resolve(self, _next: Callable, root: Any, info: GraphQLResolveInfo, *args: str, **kwargs: Any) -> AwaitableOrValue[Any]:
        ...
    


def process_directive(directive: DirectiveNode, value: Any, info: GraphQLResolveInfo) -> tuple[StrawberryDirective, dict[str, Any]]:
    """Get a `StrawberryDirective` from ``directive` and prepare its arguments."""
    ...

__all__ = ["DirectivesExtension", "DirectivesExtensionSync"]
