"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterator
from strawberry.extensions.base_extension import SchemaExtension

class DisableValidation(SchemaExtension):
    """Disable query validation.

    Example:

    ```python
    import strawberry
    from strawberry.extensions import DisableValidation

    schema = strawberry.Schema(
        Query,
        extensions=[
            DisableValidation,
        ],
    )
    ```
    """
    def __init__(self) -> None:
        ...
    
    def on_operation(self) -> Iterator[None]:
        ...
    


__all__ = ["DisableValidation"]
