"""
This type stub file was generated by pyright.
"""

from collections.abc import Awaitable, Callable
from functools import cached_property
from typing import Any, TYPE_CHECKING, TypeAlias
from strawberry.types import Info
from strawberry.types.field import StrawberryField

if TYPE_CHECKING:
    ...
SyncExtensionResolver: TypeAlias = Callable[..., Any]
AsyncExtensionResolver: TypeAlias = Callable[..., Awaitable[Any]]
class FieldExtension:
    def apply(self, field: StrawberryField) -> None:
        ...
    
    def resolve(self, next_: SyncExtensionResolver, source: Any, info: Info, **kwargs: Any) -> Any:
        ...
    
    async def resolve_async(self, next_: AsyncExtensionResolver, source: Any, info: Info, **kwargs: Any) -> Any:
        ...
    
    @cached_property
    def supports_sync(self) -> bool:
        ...
    
    @cached_property
    def supports_async(self) -> bool:
        ...
    


class SyncToAsyncExtension(FieldExtension):
    """Helper class for mixing async extensions with sync resolvers.

    Applied automatically.
    """
    async def resolve_async(self, next_: AsyncExtensionResolver, source: Any, info: Info, **kwargs: Any) -> Any:
        ...
    


def build_field_extension_resolvers(field: StrawberryField) -> list[SyncExtensionResolver | AsyncExtensionResolver]:
    """Builds a list of resolvers for a field with extensions.

    Verifies that all of the field extensions for a given field support
    sync or async depending on the field resolver.

    Inserts a SyncToAsyncExtension to be able to use Async extensions on sync resolvers
    Throws a TypeError otherwise.

    Returns True if resolving should be async, False on sync resolving
    based on the resolver and extensions
    """
    ...

__all__ = ["FieldExtension"]
