"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Iterator
from graphql.error import GraphQLError
from strawberry.extensions.base_extension import SchemaExtension

def default_should_mask_error(_: GraphQLError) -> bool:
    ...

class MaskErrors(SchemaExtension):
    should_mask_error: Callable[[GraphQLError], bool]
    error_message: str
    def __init__(self, should_mask_error: Callable[[GraphQLError], bool] = ..., error_message: str = ...) -> None:
        ...
    
    def anonymise_error(self, error: GraphQLError) -> GraphQLError:
        ...
    
    def on_operation(self) -> Iterator[None]:
        ...
    


