"""
This type stub file was generated by pyright.
"""

from graphql import ExecutableDefinitionNode, FieldNode, InlineFragmentNode, ValidationRule
from strawberry.extensions.add_validation_rules import AddValidationRules

class MaxAliasesLimiter(AddValidationRules):
    """Add a validator to limit the number of aliases used.

    Example:

    ```python
    import strawberry
    from strawberry.extensions import MaxAliasesLimiter

    schema = strawberry.Schema(Query, extensions=[MaxAliasesLimiter(max_alias_count=15)])
    ```
    """
    def __init__(self, max_alias_count: int) -> None:
        """Initialize the MaxAliasesLimiter.

        Args:
            max_alias_count: The maximum number of aliases allowed in a GraphQL document.
        """
        ...
    


def create_validator(max_alias_count: int) -> type[ValidationRule]:
    """Create a validator that checks the number of aliases in a document.

    Args:
        max_alias_count: The maximum number of aliases allowed in a GraphQL document.
    """
    class MaxAliasesValidator(ValidationRule):
        ...
    
    

def count_fields_with_alias(selection_set_owner: ExecutableDefinitionNode | FieldNode | InlineFragmentNode) -> int:
    ...

__all__ = ["MaxAliasesLimiter"]
