"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterator
from strawberry.extensions.base_extension import SchemaExtension

class ParserCache(SchemaExtension):
    """Add LRU caching the parsing step during execution to improve performance.

    Example:

    ```python
    import strawberry
    from strawberry.extensions import ParserCache

    schema = strawberry.Schema(
        Query,
        extensions=[
            ParserCache(maxsize=100),
        ],
    )
    ```
    """
    def __init__(self, maxsize: int | None = ...) -> None:
        """Initialize the ParserCache.

        Args:
            maxsize: Set the maxsize of the cache. If `maxsize` is set to `None` then the
                cache will grow without bound.
                More info: https://docs.python.org/3/library/functools.html#functools.lru_cache
        """
        ...
    
    def on_parse(self) -> Iterator[None]:
        ...
    


__all__ = ["ParserCache"]
