"""
This type stub file was generated by pyright.
"""

import re
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from typing import TYPE_CHECKING, TypeAlias
from graphql.language import DefinitionNode, FieldNode, FragmentDefinitionNode, Node, OperationDefinitionNode, ValueNode
from graphql.validation import ValidationContext, ValidationRule
from strawberry.extensions import AddValidationRules

if TYPE_CHECKING:
    ...
IgnoreType: TypeAlias = Callable[[str], bool] | re.Pattern | str
FieldArgumentType: TypeAlias = (bool | int | float | str | list["FieldArgumentType"] | dict[str, "FieldArgumentType"])
FieldArgumentsType: TypeAlias = dict[str, FieldArgumentType]
@dataclass
class IgnoreContext:
    field_name: str
    field_args: FieldArgumentsType
    node: Node
    context: ValidationContext
    ...


ShouldIgnoreType = Callable[[IgnoreContext], bool]
class QueryDepthLimiter(AddValidationRules):
    """Add a validator to limit the query depth of GraphQL operations.

    Example:

    ```python
    import strawberry
    from strawberry.extensions import QueryDepthLimiter

    schema = strawberry.Schema(
        Query,
        extensions=[QueryDepthLimiter(max_depth=4)],
    )
    ```
    """
    def __init__(self, max_depth: int, callback: Callable[[dict[str, int]], None] | None = ..., should_ignore: ShouldIgnoreType | None = ...) -> None:
        """Initialize the QueryDepthLimiter.

        Args:
            max_depth: The maximum allowed depth for any operation in a GraphQL document.
            callback: Called each time validation runs.
                Receives an Object which is a map of the depths for each operation.
            should_ignore: Stops recursive depth checking based on a field name and arguments.
                A function that returns a boolean and conforms to the ShouldIgnoreType function signature.
        """
        ...
    


def create_validator(max_depth: int, should_ignore: ShouldIgnoreType | None, callback: Callable[[dict[str, int]], None] | None = ...) -> type[ValidationRule]:
    class DepthLimitValidator(ValidationRule):
        ...
    
    

def get_fragments(definitions: Iterable[DefinitionNode]) -> dict[str, FragmentDefinitionNode]:
    ...

def get_queries_and_mutations(definitions: Iterable[DefinitionNode]) -> dict[str, OperationDefinitionNode]:
    ...

def get_field_name(node: FieldNode) -> str:
    ...

def resolve_field_value(value: ValueNode) -> FieldArgumentType:
    ...

def get_field_arguments(node: FieldNode) -> FieldArgumentsType:
    ...

def determine_depth(node: Node, fragments: dict[str, FragmentDefinitionNode], depth_so_far: int, max_depth: int, context: ValidationContext, operation_name: str, should_ignore: ShouldIgnoreType | None) -> int:
    ...

def is_ignored(node: FieldNode, ignore: list[IgnoreType] | None = ...) -> bool:
    ...

__all__ = ["QueryDepthLimiter"]
