"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from strawberry.extensions.context import ExecutingContextManager, OperationContextManager, ParsingContextManager, ValidationContextManager
from strawberry.types import ExecutionContext
from . import SchemaExtension

if TYPE_CHECKING:
    ...
class SchemaExtensionsRunner:
    extensions: list[SchemaExtension]
    def __init__(self, execution_context: ExecutionContext, extensions: list[SchemaExtension] | None = ...) -> None:
        ...
    
    def operation(self) -> OperationContextManager:
        ...
    
    def validation(self) -> ValidationContextManager:
        ...
    
    def parsing(self) -> ParsingContextManager:
        ...
    
    def executing(self) -> ExecutingContextManager:
        ...
    
    def get_extensions_results_sync(self) -> dict[str, Any]:
        ...
    
    async def get_extensions_results(self, ctx: ExecutionContext) -> dict[str, Any]:
        ...
    


