"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from graphql import GraphQLResolveInfo

if TYPE_CHECKING:
    ...
def is_introspection_key(key: str | int) -> bool:
    ...

def is_introspection_field(info: GraphQLResolveInfo) -> bool:
    ...

def get_path_from_info(info: GraphQLResolveInfo) -> list[str]:
    ...

__all__ = ["get_path_from_info", "is_introspection_field", "is_introspection_key"]
