"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterator
from strawberry.extensions.base_extension import SchemaExtension

class ValidationCache(SchemaExtension):
    """Add LRU caching the validation step during execution to improve performance.

    Example:
    ```python
    import strawberry
    from strawberry.extensions import ValidationCache

    schema = strawberry.Schema(
        Query,
        extensions=[
            ValidationCache(maxsize=100),
        ],
    )
    ```
    """
    def __init__(self, maxsize: int | None = ...) -> None:
        """Initialize the ValidationCache.

        Args:
            maxsize: Set the maxsize of the cache. If `maxsize` is set to `None` then the
                cache will grow without bound.

        More info: https://docs.python.org/3/library/functools.html#functools.lru_cache
        """
        ...
    
    def on_validate(self) -> Iterator[None]:
        ...
    


__all__ = ["ValidationCache"]
