"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING, TypeVar
from strawberry.types.base import StrawberryList, StrawberryMaybe, StrawberryObjectDefinition, StrawberryOptional, StrawberryType, StrawberryTypeVar
from strawberry.types.enum import StrawberryEnumDefinition
from strawberry.types.field import StrawberryField
from strawberry.types.union import StrawberryUnion

if TYPE_CHECKING:
    ...
ASYNC_TYPES = ...
class StrawberryAnnotation:
    __slots__ = ...
    def __init__(self, annotation: object | str, *, namespace: dict[str, Any] | None = ...) -> None:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    
    @staticmethod
    def from_annotation(annotation: object, namespace: dict[str, Any] | None = ...) -> StrawberryAnnotation | None:
        ...
    
    @property
    def annotation(self) -> object | str:
        """Return evaluated type on success or fallback to raw (string) annotation."""
        ...
    
    @annotation.setter
    def annotation(self, value: object | str) -> None:
        ...
    
    def evaluate(self) -> type:
        """Return evaluated annotation using `strawberry.util.typing.eval_type`."""
        ...
    
    def resolve(self, *, type_definition: StrawberryObjectDefinition | None = ...) -> StrawberryType | type:
        """Return resolved (transformed) annotation."""
        ...
    
    def set_namespace_from_field(self, field: StrawberryField) -> None:
        ...
    
    def create_concrete_type(self, evaled_type: type) -> type:
        ...
    
    def create_enum(self, evaled_type: Any) -> StrawberryEnumDefinition:
        ...
    
    def create_list(self, evaled_type: Any) -> StrawberryList:
        ...
    
    def create_optional(self, evaled_type: Any) -> StrawberryOptional:
        ...
    
    def create_maybe(self, evaled_type: Any) -> StrawberryMaybe:
        ...
    
    def create_type_var(self, evaled_type: TypeVar) -> StrawberryTypeVar:
        ...
    
    def create_union(self, evaled_type: type[Any], args: list[Any]) -> StrawberryUnion:
        ...
    


__all__ = ["StrawberryAnnotation"]
