"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from asyncio.futures import Future
from dataclasses import dataclass
from typing import Any, Generic, TYPE_CHECKING, TypeVar, overload
from asyncio.events import AbstractEventLoop
from collections.abc import Awaitable, Callable, Hashable, Iterable, Mapping, Sequence

if TYPE_CHECKING:
    ...
T = TypeVar("T")
K = TypeVar("K")
@dataclass
class LoaderTask(Generic[K, T]):
    key: K
    future: Future
    ...


@dataclass
class Batch(Generic[K, T]):
    tasks: list[LoaderTask] = ...
    dispatched: bool = ...
    def add_task(self, key: Any, future: Future) -> None:
        ...
    
    def __len__(self) -> int:
        ...
    


class AbstractCache(ABC, Generic[K, T]):
    @abstractmethod
    def get(self, key: K) -> Future[T] | None:
        ...
    
    @abstractmethod
    def set(self, key: K, value: Future[T]) -> None:
        ...
    
    @abstractmethod
    def delete(self, key: K) -> None:
        ...
    
    @abstractmethod
    def clear(self) -> None:
        ...
    


class DefaultCache(AbstractCache[K, T]):
    def __init__(self, cache_key_fn: Callable[[K], Hashable] | None = ...) -> None:
        ...
    
    def get(self, key: K) -> Future[T] | None:
        ...
    
    def set(self, key: K, value: Future[T]) -> None:
        ...
    
    def delete(self, key: K) -> None:
        ...
    
    def clear(self) -> None:
        ...
    


class DataLoader(Generic[K, T]):
    batch: Batch[K, T] | None = ...
    cache: bool = ...
    cache_map: AbstractCache[K, T]
    @overload
    def __init__(self, load_fn: Callable[[list[K]], Awaitable[Sequence[T | BaseException]]], max_batch_size: int | None = ..., cache: bool = ..., loop: AbstractEventLoop | None = ..., cache_map: AbstractCache[K, T] | None = ..., cache_key_fn: Callable[[K], Hashable] | None = ...) -> None:
        ...
    
    @overload
    def __init__(self: DataLoader[K, Any], load_fn: Callable[[list[K]], Awaitable[list[Any]]], max_batch_size: int | None = ..., cache: bool = ..., loop: AbstractEventLoop | None = ..., cache_map: AbstractCache[K, T] | None = ..., cache_key_fn: Callable[[K], Hashable] | None = ...) -> None:
        ...
    
    def __init__(self, load_fn: Callable[[list[K]], Awaitable[Sequence[T | BaseException]]], max_batch_size: int | None = ..., cache: bool = ..., loop: AbstractEventLoop | None = ..., cache_map: AbstractCache[K, T] | None = ..., cache_key_fn: Callable[[K], Hashable] | None = ...) -> None:
        ...
    
    @property
    def loop(self) -> AbstractEventLoop:
        ...
    
    def load(self, key: K) -> Awaitable[T]:
        ...
    
    def load_many(self, keys: Iterable[K]) -> Awaitable[list[T]]:
        ...
    
    def clear(self, key: K) -> None:
        ...
    
    def clear_many(self, keys: Iterable[K]) -> None:
        ...
    
    def clear_all(self) -> None:
        ...
    
    def prime(self, key: K, value: T, force: bool = ...) -> None:
        ...
    
    def prime_many(self, data: Mapping[K, T], force: bool = ...) -> None:
        ...
    


def should_create_new_batch(loader: DataLoader, batch: Batch) -> bool:
    ...

def get_current_batch(loader: DataLoader) -> Batch:
    ...

def dispatch(loader: DataLoader, batch: Batch) -> None:
    ...

async def dispatch_batch(loader: DataLoader, batch: Batch) -> None:
    ...

__all__ = ["AbstractCache", "Batch", "DataLoader", "DefaultCache", "LoaderTask", "dispatch", "dispatch_batch", "get_current_batch", "should_create_new_batch"]
