"""
This type stub file was generated by pyright.
"""

import dataclasses
import inspect
from functools import cached_property
from typing import Annotated, Any, Generic, TYPE_CHECKING, TypeVar
from graphql import DirectiveLocation
from strawberry.types.fields.resolver import StrawberryResolver
from collections.abc import Callable
from strawberry.types.arguments import StrawberryArgument

if TYPE_CHECKING:
    ...
def directive_field(name: str, default: object = ...) -> Any:
    """Function to add metadata to a directive argument, like the GraphQL name.

    Args:
        name: The GraphQL name of the directive argument
        default: The default value of the argument

    Returns:
        A StrawberryField object that can be used to customise a directive argument

    Example:
    ```python
    import strawberry
    from strawberry.schema_directive import Location


    @strawberry.schema_directive(locations=[Location.FIELD_DEFINITION])
    class Sensitive:
        reason: str = strawberry.directive_field(name="as")
    ```
    """
    ...

T = TypeVar("T")
class StrawberryDirectiveValue:
    ...


DirectiveValue = Annotated[T, StrawberryDirectiveValue()]
VALUE_PARAMSPEC = ...
class StrawberryDirectiveResolver(StrawberryResolver[T]):
    RESERVED_PARAMSPEC = ...
    @cached_property
    def value_parameter(self) -> inspect.Parameter | None:
        ...
    


@dataclasses.dataclass
class StrawberryDirective(Generic[T]):
    python_name: str
    graphql_name: str | None
    resolver: StrawberryDirectiveResolver[T]
    locations: list[DirectiveLocation]
    description: str | None = ...
    @cached_property
    def arguments(self) -> list[StrawberryArgument]:
        ...
    


def directive(*, locations: list[DirectiveLocation], description: str | None = ..., name: str | None = ...) -> Callable[[Callable[..., T]], StrawberryDirective[T]]:
    """Decorator to create a GraphQL operation directive.

    Args:
        locations: The locations where the directive can be used
        description: The GraphQL description of the directive
        name: The GraphQL name of the directive

    Returns:
        A StrawberryDirective object that can be used to customise a directive

    Example:
    ```python
    import strawberry
    from strawberry.directive import DirectiveLocation


    @strawberry.directive(
        locations=[DirectiveLocation.FIELD], description="Make string uppercase"
    )
    def turn_uppercase(value: str):
        return value.upper()
    ```
    """
    ...

__all__ = ["DirectiveLocation", "StrawberryDirective", "directive"]
