"""
This type stub file was generated by pyright.
"""

from typing import Annotated, Any, TypeVar

_parent_re = ...
class StrawberryParent:
    ...


T = TypeVar("T")
Parent = Annotated[T, StrawberryParent()]
def resolve_parent_forward_arg(annotation: Any) -> Any:
    ...

__all__ = ["Parent", "StrawberryParent", "resolve_parent_forward_arg"]
