"""
This type stub file was generated by pyright.
"""

import abc
from functools import cached_property
from typing import Any, TYPE_CHECKING
from strawberry.extensions import FieldExtension
from collections.abc import Awaitable
from graphql import GraphQLError, GraphQLErrorExtensions
from strawberry.extensions.field_extension import AsyncExtensionResolver, SyncExtensionResolver
from strawberry.types import Info
from strawberry.types.field import StrawberryField

if TYPE_CHECKING:
    ...
class BasePermission(abc.ABC):
    """Base class for permissions. All permissions should inherit from this class.

    Example:

    ```python
    from strawberry.permission import BasePermission


    class IsAuthenticated(BasePermission):
        message = "User is not authenticated"

        def has_permission(self, source, info, **kwargs):
            return info.context["user"].is_authenticated
    ```
    """
    message: str | None = ...
    error_extensions: GraphQLErrorExtensions | None = ...
    error_class: type[GraphQLError] = ...
    _schema_directive: object | None = ...
    @abc.abstractmethod
    def has_permission(self, source: Any, info: Info, **kwargs: Any) -> bool | Awaitable[bool]:
        """Check if the permission should be accepted.

        This method should be overridden by the subclasses.
        """
        ...
    
    def on_unauthorized(self) -> None:
        """Default error raising for permissions.

        This method can be overridden to customize the error raised when the permission is not granted.

        Example:

        ```python
        from strawberry.permission import BasePermission


        class CustomPermissionError(PermissionError):
            pass


        class IsAuthenticated(BasePermission):
            message = "User is not authenticated"

            def has_permission(self, source, info, **kwargs):
                return info.context["user"].is_authenticated

            def on_unauthorized(self) -> None:
                raise CustomPermissionError(self.message)
        ```
        """
        ...
    
    @property
    def schema_directive(self) -> object:
        ...
    


class PermissionExtension(FieldExtension):
    """Handles permissions for a field.

    Instantiate this as a field extension with all of the permissions you want to apply.

    Note:
        Currently, this is automatically added to the field, when using field.permission_classes

    This is deprecated behaviour, please manually add the extension to field.extensions
    """
    def __init__(self, permissions: list[BasePermission], use_directives: bool = ..., fail_silently: bool = ...) -> None:
        """Initialize the permission extension.

        Args:
            permissions: List of permissions to apply.
            fail_silently: If True, return None or [] instead of raising an exception.
                This is only valid for optional or list fields.
            use_directives: If True, add schema directives to the field.
        """
        ...
    
    def apply(self, field: StrawberryField) -> None:
        """Applies all of the permission directives (deduped) to the schema and sets up silent permissions."""
        ...
    
    def resolve(self, next_: SyncExtensionResolver, source: Any, info: Info, **kwargs: dict[str, Any]) -> Any:
        """Checks if the permission should be accepted and raises an exception if not."""
        ...
    
    async def resolve_async(self, next_: AsyncExtensionResolver, source: Any, info: Info, **kwargs: dict[str, Any]) -> Any:
        ...
    
    @cached_property
    def supports_sync(self) -> bool:
        """Whether this extension can be resolved synchronously or not.

        The Permission extension always supports async checking using await_maybe,
        but only supports sync checking if there are no async permissions.
        """
        ...
    


__all__ = ["BasePermission", "PermissionExtension"]
