"""
This type stub file was generated by pyright.
"""

from typing import Any, NewType, TYPE_CHECKING
from collections.abc import Mapping
from strawberry.types.scalar import ScalarDefinition, ScalarWrapper

if TYPE_CHECKING:
    ...
ID = NewType("ID", str)
JSON = NewType("JSON", object)
Base16 = NewType("Base16", bytes)
Base32 = NewType("Base32", bytes)
Base64 = NewType("Base64", bytes)
def is_scalar(annotation: Any, scalar_registry: Mapping[object, ScalarWrapper | ScalarDefinition]) -> bool:
    ...

__all__ = ["ID", "JSON", "Base16", "Base32", "Base64", "is_scalar"]
