"""
This type stub file was generated by pyright.
"""

from collections.abc import AsyncGenerator
from typing import Annotated, TypeVar

class StrawberryStreamable:
    ...


T = TypeVar("T")
Streamable = Annotated[AsyncGenerator[T, None], StrawberryStreamable()]
__all__ = ["Streamable"]
