"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from graphql.language import ValueNode
from graphql.type import GraphQLInputType

if TYPE_CHECKING:
    ...
__all__ = ["ast_from_value"]
_re_integer_string = ...
def ast_from_leaf_type(serialized: object, type_: GraphQLInputType | None) -> ValueNode:
    ...

def ast_from_value(value: Any, type_: GraphQLInputType) -> ValueNode | None:
    ...

__all__ = ["ast_from_value"]
