"""
This type stub file was generated by pyright.
"""

import dataclasses
from typing import Any, TYPE_CHECKING, TypeVar
from graphql import GraphQLArgument, GraphQLEnumType, GraphQLEnumValue, GraphQLObjectType, GraphQLScalarType, GraphQLUnionType
from graphql.type.directives import GraphQLDirective
from strawberry.schema import BaseSchema
from strawberry.types.field import StrawberryField

if TYPE_CHECKING:
    ...
_T = TypeVar("_T")
@dataclasses.dataclass
class PrintExtras:
    directives: set[str] = ...
    types: set[type] = ...


def print_schema_directive_params(directive: GraphQLDirective, values: dict[str, Any], *, schema: BaseSchema) -> str:
    ...

def print_schema_directive(directive: Any, schema: BaseSchema, *, extras: PrintExtras) -> str:
    ...

def print_field_directives(field: StrawberryField | None, schema: BaseSchema, *, extras: PrintExtras) -> str:
    ...

def print_argument_directives(argument: GraphQLArgument, *, schema: BaseSchema, extras: PrintExtras) -> str:
    ...

def print_args(args: dict[str, GraphQLArgument], indentation: str = ..., *, schema: BaseSchema, extras: PrintExtras) -> str:
    ...

def print_fields(type_: GraphQLObjectType, schema: BaseSchema, *, extras: PrintExtras) -> str:
    ...

def print_scalar(type_: GraphQLScalarType, *, schema: BaseSchema, extras: PrintExtras) -> str:
    ...

def print_enum_value(name: str, value: GraphQLEnumValue, first_in_block: bool, *, schema: BaseSchema, extras: PrintExtras) -> str:
    ...

def print_enum(type_: GraphQLEnumType, *, schema: BaseSchema, extras: PrintExtras) -> str:
    ...

def print_extends(type_: GraphQLObjectType, schema: BaseSchema) -> str:
    ...

def print_type_directives(type_: GraphQLObjectType, schema: BaseSchema, *, extras: PrintExtras) -> str:
    ...

def print_input_value(name: str, arg: GraphQLArgument) -> str:
    ...

def print_union(type_: GraphQLUnionType, *, schema: BaseSchema, extras: PrintExtras) -> str:
    ...

def print_schema_directives(schema: BaseSchema, *, extras: PrintExtras) -> str:
    ...

def print_schema_definition(schema: BaseSchema, *, extras: PrintExtras) -> str | None:
    ...

def print_directive(directive: GraphQLDirective, *, schema: BaseSchema) -> str | None:
    ...

def is_builtin_directive(directive: GraphQLDirective) -> bool:
    ...

def print_schema(schema: BaseSchema) -> str:
    ...

__all__ = ["print_schema"]
