"""
This type stub file was generated by pyright.
"""

class CodegenError(Exception):
    ...


class NoOperationProvidedError(CodegenError):
    ...


class NoOperationNameProvidedError(CodegenError):
    ...


class MultipleOperationsProvidedError(CodegenError):
    ...


__all__ = ["CodegenError", "MultipleOperationsProvidedError", "NoOperationNameProvidedError", "NoOperationProvidedError"]
