"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING
from typing_extensions import Protocol
from graphql import SelectionSetNode
from .types import GraphQLOperation, GraphQLType
from strawberry.schema import Schema

if TYPE_CHECKING:
    ...
@dataclass
class CodegenFile:
    path: str
    content: str
    ...


@dataclass
class CodegenResult:
    files: list[CodegenFile]
    def to_string(self) -> str:
        ...
    
    def write(self, folder: Path) -> None:
        ...
    


class HasSelectionSet(Protocol):
    selection_set: SelectionSetNode | None
    ...


class QueryCodegenPlugin:
    def __init__(self, query: Path) -> None:
        """Initialize the plugin.

        The singular argument is the path to the file that is being processed
        by this plugin.
        """
        ...
    
    def on_start(self) -> None:
        ...
    
    def on_end(self, result: CodegenResult) -> None:
        ...
    
    def generate_code(self, types: list[GraphQLType], operation: GraphQLOperation) -> list[CodegenFile]:
        ...
    


class ConsolePlugin:
    def __init__(self, output_dir: Path) -> None:
        ...
    
    def before_any_start(self) -> None:
        ...
    
    def after_all_finished(self) -> None:
        ...
    
    def on_start(self, plugins: Iterable[QueryCodegenPlugin], query: Path) -> None:
        ...
    
    def on_end(self, result: CodegenResult) -> None:
        ...
    


_TYPE_TO_GRAPHQL_TYPE = ...
class QueryCodegenPluginManager:
    def __init__(self, plugins: list[QueryCodegenPlugin], console_plugin: ConsolePlugin | None = ...) -> None:
        ...
    
    def generate_code(self, types: list[GraphQLType], operation: GraphQLOperation) -> CodegenResult:
        ...
    
    def on_start(self) -> None:
        ...
    
    def on_end(self, result: CodegenResult) -> None:
        ...
    


class QueryCodegen:
    def __init__(self, schema: Schema, plugins: list[QueryCodegenPlugin], console_plugin: ConsolePlugin | None = ...) -> None:
        ...
    
    def run(self, query: str) -> CodegenResult:
        ...
    
    def generate_code(self) -> CodegenResult:
        ...
    


__all__ = ["CodegenFile", "CodegenResult", "ConsolePlugin", "QueryCodegen", "QueryCodegenPlugin"]
